In [1]:
import numpy as np
import pandas as pd

In [2]:
grade=pd.read_csv('student_grade_empty.txt',sep='\t')

In [12]:
grade

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
9    林世博    NaN    NaN    NaN  387.0  10.0
10    张希    NaN  130.0  134.0  387.0  11.0
11    徐冲    NaN  124.0    NaN    NaN   NaN
12   苑宇飞    NaN  136.0  131.0  385.0  13.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0
27   张智文    NaN  116.0  125.0  350.0  28.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
..   ...    ...    ...    ...    ...   ...
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0
42    孙波   96.0  130.0   89.0    NaN  43.0
43    张良  105.0  102.0  105.0    NaN  44.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
48   张家硕  107.0   67.0  129.0    NaN  49.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

[68 rows x 6 columns]

In [4]:
grade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 6 columns):
姓名     66 non-null object
语文     59 non-null float64
数学     66 non-null float64
英语     63 non-null float64
总分     63 non-null float64
班名次    67 non-null float64
dtypes: float64(5), object(1)
memory usage: 3.3+ KB

### 缺失值处理

In [5]:
grade.数学.isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...
38    False
39    False
40    False
41     True
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
67    False
Name: 数学, Length: 68, dtype: bool

In [4]:
grade[grade.数学.isnull()] # 提取空值

     姓名     语文  数学  英语     总分   班名次
9   林世博    NaN NaN NaN  387.0  10.0
41  张俊奎  103.0 NaN NaN  317.0  42.0

In [9]:
grade[grade.数学.notnull()] # 提取非空值

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
10    张希    NaN  130.0  134.0  387.0  11.0
11    徐冲    NaN  124.0    NaN    NaN   NaN
12   苑宇飞    NaN  136.0  131.0  385.0  13.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0
27   张智文    NaN  116.0  125.0  350.0  28.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
30    何旭    NaN  113.0  120.0  347.0  31.0
..   ...    ...    ...    ...    ...   ...
37   代诗涵  105.0  105.0  126.0  336.0  38.0
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
42    孙波   96.0  130.0   89.0    NaN  43.0
43    张良  105.0  102.0  105.0    NaN  44.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
48   张家硕  107.0   67.0  129.0    NaN  49.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

[66 rows x 6 columns]

In [9]:
grade.isnull()

       姓名     语文     数学     英语     总分    班名次
0   False  False  False  False  False  False
1   False  False  False  False  False  False
2   False  False  False  False  False  False
3   False   True  False  False  False  False
4   False   True  False  False  False  False
5   False  False  False  False  False  False
6   False  False  False  False  False  False
7   False  False  False  False  False  False
8   False  False  False  False  False  False
9   False   True   True   True  False  False
10  False   True  False  False  False  False
11  False   True  False   True   True   True
12  False   True  False  False  False  False
13  False  False  False  False  False  False
14  False  False  False  False  False  False
15  False  False  False   True   True  False
16  False  False  False  False  False  False
17  False  False  False  False  False  False
18  False  False  False  False  False  False
19  False  False  False  False  False  False
20  False  False  False  False  False  False
21  False  False  False   True  False  False
22  False  False  False  False  False  False
23  False  False  False  False  False  False
24  False  False  False  False  False  False
25  False  False  False  False  False  False
26  False   True  False  False  False  False
27  False   True  False  False  False  False
28  False  False  False  False  False  False
29  False  False  False  False  False  False
..    ...    ...    ...    ...    ...    ...
38  False  False  False  False  False  False
39  False  False  False  False  False  False
40  False  False  False  False  False  False
41  False  False   True   True  False  False
42  False  False  False  False   True  False
43  False  False  False  False   True  False
44  False  False  False  False  False  False
45  False  False  False  False  False  False
46  False  False  False  False  False  False
47  False  False  False  False  False  False
48  False  False  False  False   True  False
49  False  False  False  False  False  False
50  False  False  False  False  False  False
51  False  False  False  False  False  False
52  False  False  False  False  False  False
53  False  False  False  False  False  False
54  False  False  False  False  False  False
55  False  False  False  False  False  False
56  False  False  False  False  False  False
57  False  False  False  False  False  False
58  False  False  False  False  False  False
59  False  False  False  False  False  False
60  False  False  False  False  False  False
61  False  False  False  False  False  False
62  False  False  False  False  False  False
63  False  False  False  False  False  False
64  False  False  False  False  False  False
65  False  False  False  False  False  False
66  False  False  False  False  False  False
67  False  False  False  False  False  False

[68 rows x 6 columns]

In [11]:
# 查看数据表每一列缺失的数量
np.sum(grade.isnull(),axis=0)

姓名     2
语文     9
数学     2
英语     5
总分     5
班名次    1
dtype: int64

In [11]:
grade[~grade.语文.isnull()] # 用~求not

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
31   张智凯  110.0  117.0  119.0  346.0  32.0
32   张晓爽  113.0  113.0  119.0  345.0  33.0
33   NaN  117.0  121.0  106.0  344.0  34.0
34   NaN  112.0  105.0  126.0  343.0  35.0
35   贺俊文  103.0  127.0  110.0  340.0  36.0
36  张馨月小  108.0  110.0  119.0  337.0  37.0
37   代诗涵  105.0  105.0  126.0  336.0  38.0
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0
42    孙波   96.0  130.0   89.0    NaN  43.0
43    张良  105.0  102.0  105.0    NaN  44.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
48   张家硕  107.0   67.0  129.0    NaN  49.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

In [12]:
# 提取数学和语文都为空的数据
grade[grade.数学.isnull() & grade.语文.isnull()]

    姓名  语文  数学  英语     总分   班名次
9  林世博 NaN NaN NaN  387.0  10.0

In [13]:
# 三门学科任意一门为空的数据
grade[grade.语文.isnull()|grade.数学.isnull()|grade.英语.isnull()]

     姓名     语文     数学     英语     总分   班名次
3   沙龙逸    NaN  148.0  136.0  407.0   4.0
4   李鉴学    NaN  135.0  140.0  401.0   5.0
9   林世博    NaN    NaN    NaN  387.0  10.0
10   张希    NaN  130.0  134.0  387.0  11.0
11   徐冲    NaN  124.0    NaN    NaN   NaN
12  苑宇飞    NaN  136.0  131.0  385.0  13.0
15  范作鑫  121.0  127.0    NaN    NaN  16.0
21  赵永刚  116.0  131.0    NaN  369.0  22.0
26  赵殿宇    NaN  109.0  130.0  351.0  27.0
27  张智文    NaN  116.0  125.0  350.0  28.0
30   何旭    NaN  113.0  120.0  347.0  31.0
41  张俊奎  103.0    NaN    NaN  317.0  42.0

#### 丢弃缺失值

In [14]:
# 丢弃有缺失值的列
grade.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]

[68 rows x 0 columns]

In [15]:
# 丢弃全为缺失值的那些列
grade.dropna(axis=1,how='all')

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
9    林世博    NaN    NaN    NaN  387.0  10.0
10    张希    NaN  130.0  134.0  387.0  11.0
11    徐冲    NaN  124.0    NaN    NaN   NaN
12   苑宇飞    NaN  136.0  131.0  385.0  13.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0
27   张智文    NaN  116.0  125.0  350.0  28.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
..   ...    ...    ...    ...    ...   ...
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0
42    孙波   96.0  130.0   89.0    NaN  43.0
43    张良  105.0  102.0  105.0    NaN  44.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
48   张家硕  107.0   67.0  129.0    NaN  49.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

[68 rows x 6 columns]

In [14]:
# 丢弃姓名有缺失值的行
grade.dropna(subset=['姓名'])

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
9    林世博    NaN    NaN    NaN  387.0  10.0
10    张希    NaN  130.0  134.0  387.0  11.0
11    徐冲    NaN  124.0    NaN    NaN   NaN
12   苑宇飞    NaN  136.0  131.0  385.0  13.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0
27   张智文    NaN  116.0  125.0  350.0  28.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
..   ...    ...    ...    ...    ...   ...
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0
42    孙波   96.0  130.0   89.0    NaN  43.0
43    张良  105.0  102.0  105.0    NaN  44.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
48   张家硕  107.0   67.0  129.0    NaN  49.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

[66 rows x 6 columns]

In [17]:
grade.dropna(subset=['姓名','班名次','总分'])

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
9    林世博    NaN    NaN    NaN  387.0  10.0
10    张希    NaN  130.0  134.0  387.0  11.0
12   苑宇飞    NaN  136.0  131.0  385.0  13.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0
27   张智文    NaN  116.0  125.0  350.0  28.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
30    何旭    NaN  113.0  120.0  347.0  31.0
31   张智凯  110.0  117.0  119.0  346.0  32.0
..   ...    ...    ...    ...    ...   ...
35   贺俊文  103.0  127.0  110.0  340.0  36.0
36  张馨月小  108.0  110.0  119.0  337.0  37.0
37   代诗涵  105.0  105.0  126.0  336.0  38.0
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

[61 rows x 6 columns]

In [18]:
# 样本数据中至少有3个非空值，则保留样本，否则就删除
grade.dropna(thresh=3)

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
9    林世博    NaN    NaN    NaN  387.0  10.0
10    张希    NaN  130.0  134.0  387.0  11.0
12   苑宇飞    NaN  136.0  131.0  385.0  13.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0
27   张智文    NaN  116.0  125.0  350.0  28.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
30    何旭    NaN  113.0  120.0  347.0  31.0
..   ...    ...    ...    ...    ...   ...
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0
42    孙波   96.0  130.0   89.0    NaN  43.0
43    张良  105.0  102.0  105.0    NaN  44.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
48   张家硕  107.0   67.0  129.0    NaN  49.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

[67 rows x 6 columns]

In [16]:
# 按照比例删除，如果有效值不到50%，则删除列
def test(x):
    if x<120:
        return np.nan
    else:
        return x

In [17]:
grade['英语空值']=grade.英语.map(test)
grade

      姓名     语文     数学     英语     总分   班名次   英语空值
0     杨璐  131.0  143.0  144.0  418.0   1.0  144.0
1     王雪  131.0  135.0  144.0  410.0   2.0  144.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0  142.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0  136.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0  140.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0  138.0
6     刘帅  116.0  143.0  140.0  399.0   7.0  140.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0  139.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0  135.0
9    林世博    NaN    NaN    NaN  387.0  10.0    NaN
10    张希    NaN  130.0  134.0  387.0  11.0  134.0
11    徐冲    NaN  124.0    NaN    NaN   NaN    NaN
12   苑宇飞    NaN  136.0  131.0  385.0  13.0  131.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0  139.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0  139.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0    NaN
16   裴子翔  111.0  139.0  128.0  378.0  17.0  128.0
17   武传禹  119.0  129.0  130.0  378.0  18.0  130.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0  144.0
19    刘姗  124.0  128.0  122.0  374.0  20.0  122.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0  128.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0    NaN
22  张馨月大  114.0  124.0  122.0  360.0  23.0  122.0
23   张曦月  116.0  123.0  119.0  358.0  24.0    NaN
24   胡丁文  116.0  122.0  118.0  356.0  25.0    NaN
25   赵美欣  118.0  126.0  111.0  355.0  26.0    NaN
26   赵殿宇    NaN  109.0  130.0  351.0  27.0  130.0
27   张智文    NaN  116.0  125.0  350.0  28.0  125.0
28    李季  114.0  117.0  118.0  349.0  29.0    NaN
29   杨加晖  110.0  102.0  136.0  348.0  30.0  136.0
..   ...    ...    ...    ...    ...   ...    ...
38    艾宇  115.0  111.0  106.0  332.0  39.0    NaN
39   黄俊焯  101.0  112.0  106.0  319.0  40.0    NaN
40   邹建志   98.0  104.0  116.0  318.0  41.0    NaN
41   张俊奎  103.0    NaN    NaN  317.0  42.0    NaN
42    孙波   96.0  130.0   89.0    NaN  43.0    NaN
43    张良  105.0  102.0  105.0    NaN  44.0    NaN
44   王春月  118.0   82.0  112.0  312.0  45.0    NaN
45   代明哲  101.0   91.0  115.0  307.0  46.0    NaN
46   张开羽  112.0   90.0  104.0  306.0  47.0    NaN
47   狄建译  109.0   68.0  126.0  303.0  48.0  126.0
48   张家硕  107.0   67.0  129.0    NaN  49.0  129.0
49    郭娜   94.0   98.0  104.0  296.0  50.0    NaN
50    周坤  107.0   76.0  104.0  287.0  51.0    NaN
51    洪禹  106.0  100.0   80.0  286.0  52.0    NaN
52   王治超  105.0   95.0   82.0  282.0  53.0    NaN
53   臧云飞  101.0   59.0  108.0  268.0  54.0    NaN
54   袁茂哲   85.0   95.0   85.0  265.0  55.0    NaN
55   丁婉艺   95.0   71.0   85.0  251.0  56.0    NaN
56   于娇莹   97.0   76.0   71.0  244.0  57.0    NaN
57   刘旭辉   99.0   87.0   44.0  230.0  58.0    NaN
58   张宇婷   83.0   61.0   71.0  215.0  59.0    NaN
59   黄明涛   87.0   77.0   43.0  207.0  60.0    NaN
60   吕文卓   82.0   53.0   62.0  197.0  61.0    NaN
61   王晟煜   79.0   49.0   64.0  192.0  62.0    NaN
62   孙龙基   99.0   21.0   67.0  187.0  63.0    NaN
63    赵森   90.0   29.0   64.0  183.0  64.0    NaN
64   满朝升   78.0   45.0   47.0  170.0  65.0    NaN
65   李忠浩   86.0   32.0   46.0  164.0  66.0    NaN
66   侯禹志   75.0   23.0   34.0  132.0  67.0    NaN
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0    NaN

[68 rows x 7 columns]

In [18]:
np.sum(grade.英语空值.isnull())

41

In [27]:
grade.shape[0]*0.5

34.0

In [28]:
# 超过50%的空值的数据会被删除
grade.dropna(axis=1,thresh=grade.shape[0]*0.5)

      姓名     语文     数学     英语     总分   班名次
0     杨璐  131.0  143.0  144.0  418.0   1.0
1     王雪  131.0  135.0  144.0  410.0   2.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0
6     刘帅  116.0  143.0  140.0  399.0   7.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0
9    林世博    NaN    NaN    NaN  387.0  10.0
10    张希    NaN  130.0  134.0  387.0  11.0
11    徐冲    NaN  124.0    NaN    NaN   NaN
12   苑宇飞    NaN  136.0  131.0  385.0  13.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0
17   武传禹  119.0  129.0  130.0  378.0  18.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0
19    刘姗  124.0  128.0  122.0  374.0  20.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0
23   张曦月  116.0  123.0  119.0  358.0  24.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0
27   张智文    NaN  116.0  125.0  350.0  28.0
28    李季  114.0  117.0  118.0  349.0  29.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0
..   ...    ...    ...    ...    ...   ...
38    艾宇  115.0  111.0  106.0  332.0  39.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0
40   邹建志   98.0  104.0  116.0  318.0  41.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0
42    孙波   96.0  130.0   89.0    NaN  43.0
43    张良  105.0  102.0  105.0    NaN  44.0
44   王春月  118.0   82.0  112.0  312.0  45.0
45   代明哲  101.0   91.0  115.0  307.0  46.0
46   张开羽  112.0   90.0  104.0  306.0  47.0
47   狄建译  109.0   68.0  126.0  303.0  48.0
48   张家硕  107.0   67.0  129.0    NaN  49.0
49    郭娜   94.0   98.0  104.0  296.0  50.0
50    周坤  107.0   76.0  104.0  287.0  51.0
51    洪禹  106.0  100.0   80.0  286.0  52.0
52   王治超  105.0   95.0   82.0  282.0  53.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0
63    赵森   90.0   29.0   64.0  183.0  64.0
64   满朝升   78.0   45.0   47.0  170.0  65.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0

[68 rows x 6 columns]

#### 填充缺失值

In [30]:
# 固定值填充
grade.语文=grade.语文.fillna(0)

In [31]:
np.sum(grade.语文.isnull())

0

In [32]:
# 平均数填充
grade.数学.fillna(grade.数学.mean())

0     143.000000
1     135.000000
2     139.000000
3     148.000000
4     135.000000
5     133.000000
6     143.000000
7     142.000000
8     139.000000
9     102.227273
10    130.000000
11    124.000000
12    136.000000
13    123.000000
14    115.000000
15    127.000000
16    139.000000
17    129.000000
18    108.000000
19    128.000000
20    123.000000
21    131.000000
22    124.000000
23    123.000000
24    122.000000
25    126.000000
26    109.000000
27    116.000000
28    117.000000
29    102.000000
         ...
38    111.000000
39    112.000000
40    104.000000
41    102.227273
42    130.000000
43    102.000000
44     82.000000
45     91.000000
46     90.000000
47     68.000000
48     67.000000
49     98.000000
50     76.000000
51    100.000000
52     95.000000
53     59.000000
54     95.000000
55     71.000000
56     76.000000
57     87.000000
58     61.000000
59     77.000000
60     53.000000
61     49.000000
62     21.000000
63     29.000000
64     45.000000
65     32.000000
66     23.000000
67     23.000000
Name: 数学, Length: 68, dtype: float64

In [19]:
grade.数学.mode()

0    123.0
1    139.0
dtype: float64

In [20]:
grade.数学.median()

111.5

In [54]:
# 众数填充
grade.数学.fillna(grade.数学.mode()[0]) # median中位数填充

0     143.0
1     135.0
2     139.0
3     148.0
4     135.0
5     133.0
6     143.0
7     142.0
8     139.0
9     123.0
10    130.0
11    124.0
12    136.0
13    123.0
14    115.0
15    127.0
16    139.0
17    129.0
18    108.0
19    128.0
20    123.0
21    131.0
22    124.0
23    123.0
24    122.0
25    126.0
26    109.0
27    116.0
28    117.0
29    102.0
      ...
38    111.0
39    112.0
40    104.0
41    123.0
42    130.0
43    102.0
44     82.0
45     91.0
46     90.0
47     68.0
48     67.0
49     98.0
50     76.0
51    100.0
52     95.0
53     59.0
54     95.0
55     71.0
56     76.0
57     87.0
58     61.0
59     77.0
60     53.0
61     49.0
62     21.0
63     29.0
64     45.0
65     32.0
66     23.0
67     23.0
Name: 数学, Length: 68, dtype: float64

In [ ]:
# 中位数填充
grade.数学.fillna(grade.数学.median())

#### 上下文填充

In [35]:
# 下文
grade.英语.fillna(method='bfill')

0     144.0
1     144.0
2     142.0
3     136.0
4     140.0
5     138.0
6     140.0
7     139.0
8     135.0
9     134.0
10    134.0
11    131.0
12    131.0
13    139.0
14    139.0
15    128.0
16    128.0
17    130.0
18    144.0
19    122.0
20    128.0
21    122.0
22    122.0
23    119.0
24    118.0
25    111.0
26    130.0
27    125.0
28    118.0
29    136.0
      ...
38    106.0
39    106.0
40    116.0
41     89.0
42     89.0
43    105.0
44    112.0
45    115.0
46    104.0
47    126.0
48    129.0
49    104.0
50    104.0
51     80.0
52     82.0
53    108.0
54     85.0
55     85.0
56     71.0
57     44.0
58     71.0
59     43.0
60     62.0
61     64.0
62     67.0
63     64.0
64     47.0
65     46.0
66     34.0
67     34.0
Name: 英语, Length: 68, dtype: float64

In [37]:
# 上文
grade.英语.fillna(method='ffill')

0     144.0
1     144.0
2     142.0
3     136.0
4     140.0
5     138.0
6     140.0
7     139.0
8     135.0
9     135.0
10    134.0
11    134.0
12    131.0
13    139.0
14    139.0
15    139.0
16    128.0
17    130.0
18    144.0
19    122.0
20    128.0
21    128.0
22    122.0
23    119.0
24    118.0
25    111.0
26    130.0
27    125.0
28    118.0
29    136.0
      ...
38    106.0
39    106.0
40    116.0
41    116.0
42     89.0
43    105.0
44    112.0
45    115.0
46    104.0
47    126.0
48    129.0
49    104.0
50    104.0
51     80.0
52     82.0
53    108.0
54     85.0
55     85.0
56     71.0
57     44.0
58     71.0
59     43.0
60     62.0
61     64.0
62     67.0
63     64.0
64     47.0
65     46.0
66     34.0
67     34.0
Name: 英语, Length: 68, dtype: float64

#### 其他列填充

In [21]:
# 数学成绩通过语文成绩进行填充
grade['数学1']=grade.数学.fillna(grade.语文)

In [22]:
grade

      姓名     语文     数学     英语     总分   班名次   英语空值    数学1
0     杨璐  131.0  143.0  144.0  418.0   1.0  144.0  143.0
1     王雪  131.0  135.0  144.0  410.0   2.0  144.0  135.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0  142.0  139.0
3    沙龙逸    NaN  148.0  136.0  407.0   4.0  136.0  148.0
4    李鉴学    NaN  135.0  140.0  401.0   5.0  140.0  135.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0  138.0  133.0
6     刘帅  116.0  143.0  140.0  399.0   7.0  140.0  143.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0  139.0  142.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0  135.0  139.0
9    林世博    NaN    NaN    NaN  387.0  10.0    NaN    NaN
10    张希    NaN  130.0  134.0  387.0  11.0  134.0  130.0
11    徐冲    NaN  124.0    NaN    NaN   NaN    NaN  124.0
12   苑宇飞    NaN  136.0  131.0  385.0  13.0  131.0  136.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0  139.0  123.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0  139.0  115.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0    NaN  127.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0  128.0  139.0
17   武传禹  119.0  129.0  130.0  378.0  18.0  130.0  129.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0  144.0  108.0
19    刘姗  124.0  128.0  122.0  374.0  20.0  122.0  128.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0  128.0  123.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0    NaN  131.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0  122.0  124.0
23   张曦月  116.0  123.0  119.0  358.0  24.0    NaN  123.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0    NaN  122.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0    NaN  126.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0  130.0  109.0
27   张智文    NaN  116.0  125.0  350.0  28.0  125.0  116.0
28    李季  114.0  117.0  118.0  349.0  29.0    NaN  117.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0  136.0  102.0
..   ...    ...    ...    ...    ...   ...    ...    ...
38    艾宇  115.0  111.0  106.0  332.0  39.0    NaN  111.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0    NaN  112.0
40   邹建志   98.0  104.0  116.0  318.0  41.0    NaN  104.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0    NaN  103.0
42    孙波   96.0  130.0   89.0    NaN  43.0    NaN  130.0
43    张良  105.0  102.0  105.0    NaN  44.0    NaN  102.0
44   王春月  118.0   82.0  112.0  312.0  45.0    NaN   82.0
45   代明哲  101.0   91.0  115.0  307.0  46.0    NaN   91.0
46   张开羽  112.0   90.0  104.0  306.0  47.0    NaN   90.0
47   狄建译  109.0   68.0  126.0  303.0  48.0  126.0   68.0
48   张家硕  107.0   67.0  129.0    NaN  49.0  129.0   67.0
49    郭娜   94.0   98.0  104.0  296.0  50.0    NaN   98.0
50    周坤  107.0   76.0  104.0  287.0  51.0    NaN   76.0
51    洪禹  106.0  100.0   80.0  286.0  52.0    NaN  100.0
52   王治超  105.0   95.0   82.0  282.0  53.0    NaN   95.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0    NaN   59.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0    NaN   95.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0    NaN   71.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0    NaN   76.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0    NaN   87.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0    NaN   61.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0    NaN   77.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0    NaN   53.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0    NaN   49.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0    NaN   21.0
63    赵森   90.0   29.0   64.0  183.0  64.0    NaN   29.0
64   满朝升   78.0   45.0   47.0  170.0  65.0    NaN   45.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0    NaN   32.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0    NaN   23.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0    NaN   23.0

[68 rows x 8 columns]

In [41]:
# 语文和英语的平均值来填补数学
grade['数学2']=grade.数学.fillna((grade.语文+grade.英语)/2)
grade

      姓名     语文     数学     英语     总分   班名次   英语空值    数学1    数学2
0     杨璐  131.0  143.0  144.0  418.0   1.0  144.0  143.0  143.0
1     王雪  131.0  135.0  144.0  410.0   2.0  144.0  135.0  135.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0  142.0  139.0  139.0
3    沙龙逸    0.0  148.0  136.0  407.0   4.0  136.0  148.0  148.0
4    李鉴学    0.0  135.0  140.0  401.0   5.0  140.0  135.0  135.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0  138.0  133.0  133.0
6     刘帅  116.0  143.0  140.0  399.0   7.0  140.0  143.0  143.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0  139.0  142.0  142.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0  135.0  139.0  139.0
9    林世博    0.0    NaN    NaN  387.0  10.0    NaN    0.0    NaN
10    张希    0.0  130.0  134.0  387.0  11.0  134.0  130.0  130.0
11    徐冲    0.0  124.0    NaN    NaN   NaN    NaN  124.0  124.0
12   苑宇飞    0.0  136.0  131.0  385.0  13.0  131.0  136.0  136.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0  139.0  123.0  123.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0  139.0  115.0  115.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0    NaN  127.0  127.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0  128.0  139.0  139.0
17   武传禹  119.0  129.0  130.0  378.0  18.0  130.0  129.0  129.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0  144.0  108.0  108.0
19    刘姗  124.0  128.0  122.0  374.0  20.0  122.0  128.0  128.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0  128.0  123.0  123.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0    NaN  131.0  131.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0  122.0  124.0  124.0
23   张曦月  116.0  123.0  119.0  358.0  24.0    NaN  123.0  123.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0    NaN  122.0  122.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0    NaN  126.0  126.0
26   赵殿宇    0.0  109.0  130.0  351.0  27.0  130.0  109.0  109.0
27   张智文    0.0  116.0  125.0  350.0  28.0  125.0  116.0  116.0
28    李季  114.0  117.0  118.0  349.0  29.0    NaN  117.0  117.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0  136.0  102.0  102.0
..   ...    ...    ...    ...    ...   ...    ...    ...    ...
38    艾宇  115.0  111.0  106.0  332.0  39.0    NaN  111.0  111.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0    NaN  112.0  112.0
40   邹建志   98.0  104.0  116.0  318.0  41.0    NaN  104.0  104.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0    NaN  103.0    NaN
42    孙波   96.0  130.0   89.0    NaN  43.0    NaN  130.0  130.0
43    张良  105.0  102.0  105.0    NaN  44.0    NaN  102.0  102.0
44   王春月  118.0   82.0  112.0  312.0  45.0    NaN   82.0   82.0
45   代明哲  101.0   91.0  115.0  307.0  46.0    NaN   91.0   91.0
46   张开羽  112.0   90.0  104.0  306.0  47.0    NaN   90.0   90.0
47   狄建译  109.0   68.0  126.0  303.0  48.0  126.0   68.0   68.0
48   张家硕  107.0   67.0  129.0    NaN  49.0  129.0   67.0   67.0
49    郭娜   94.0   98.0  104.0  296.0  50.0    NaN   98.0   98.0
50    周坤  107.0   76.0  104.0  287.0  51.0    NaN   76.0   76.0
51    洪禹  106.0  100.0   80.0  286.0  52.0    NaN  100.0  100.0
52   王治超  105.0   95.0   82.0  282.0  53.0    NaN   95.0   95.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0    NaN   59.0   59.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0    NaN   95.0   95.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0    NaN   71.0   71.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0    NaN   76.0   76.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0    NaN   87.0   87.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0    NaN   61.0   61.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0    NaN   77.0   77.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0    NaN   53.0   53.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0    NaN   49.0   49.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0    NaN   21.0   21.0
63    赵森   90.0   29.0   64.0  183.0  64.0    NaN   29.0   29.0
64   满朝升   78.0   45.0   47.0  170.0  65.0    NaN   45.0   45.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0    NaN   32.0   32.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0    NaN   23.0   23.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0    NaN   23.0   23.0

[68 rows x 9 columns]

In [43]:
#平均值
grade.loc[:,['语文','英语']].mean(axis=1)

0     137.5
1     137.5
2     134.5
3      68.0
4      70.0
5     133.5
6     128.0
7     126.5
8     125.0
9       0.0
10     67.0
11      0.0
12     65.5
13    130.0
14    132.5
15    121.0
16    119.5
17    124.5
18    134.0
19    123.0
20    124.5
21    116.0
22    118.0
23    117.5
24    117.0
25    114.5
26     65.0
27     62.5
28    116.0
29    123.0
      ...
38    110.5
39    103.5
40    107.0
41    103.0
42     92.5
43    105.0
44    115.0
45    108.0
46    108.0
47    117.5
48    118.0
49     99.0
50    105.5
51     93.0
52     93.5
53    104.5
54     85.0
55     90.0
56     84.0
57     71.5
58     77.0
59     65.0
60     72.0
61     71.5
62     83.0
63     77.0
64     62.5
65     66.0
66     54.5
67     50.0
Length: 68, dtype: float64

#### 替换缺失值

In [24]:
grade['英语加分']=grade.英语+20

In [25]:
grade.英语加分[grade.英语加分>150]=np.nan

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [27]:
# replace
grade.replace(grade.英语加分[grade.英语加分>150],np.nan,inplace=True)
grade

      姓名     语文     数学     英语     总分   班名次   英语空值    数学1   英语加分
0     杨璐  131.0  143.0  144.0  418.0   1.0  144.0  143.0    NaN
1     王雪  131.0  135.0  144.0  410.0   2.0  144.0  135.0    NaN
2    韩林霖  127.0  139.0  142.0  408.0   3.0  142.0  139.0    NaN
3    沙龙逸    NaN  148.0  136.0  407.0   4.0  136.0  148.0    NaN
4    李鉴学    NaN  135.0  140.0  401.0   5.0  140.0  135.0    NaN
5    韩雨萌  129.0  133.0  138.0  400.0   6.0  138.0  133.0    NaN
6     刘帅  116.0  143.0  140.0  399.0   7.0  140.0  143.0    NaN
7    康惠雯  114.0  142.0  139.0  395.0   8.0  139.0  142.0    NaN
8    刘钰婷  115.0  139.0  135.0  389.0   9.0  135.0  139.0    NaN
9    林世博    NaN    NaN    NaN  387.0  10.0    NaN    NaN    NaN
10    张希    NaN  130.0  134.0  387.0  11.0  134.0  130.0    NaN
11    徐冲    NaN  124.0    NaN    NaN   NaN    NaN  124.0    NaN
12   苑宇飞    NaN  136.0  131.0  385.0  13.0  131.0  136.0    NaN
13   卢一凡  121.0  123.0  139.0  383.0  14.0  139.0  123.0    NaN
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0  139.0  115.0    NaN
15   范作鑫  121.0  127.0    NaN    NaN  16.0    NaN  127.0    NaN
16   裴子翔  111.0  139.0  128.0  378.0  17.0  128.0  139.0  148.0
17   武传禹  119.0  129.0  130.0  378.0  18.0  130.0  129.0  150.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0  144.0  108.0    NaN
19    刘姗  124.0  128.0  122.0  374.0  20.0  122.0  128.0  142.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0  128.0  123.0  148.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0    NaN  131.0    NaN
22  张馨月大  114.0  124.0  122.0  360.0  23.0  122.0  124.0  142.0
23   张曦月  116.0  123.0  119.0  358.0  24.0    NaN  123.0  139.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0    NaN  122.0  138.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0    NaN  126.0  131.0
26   赵殿宇    NaN  109.0  130.0  351.0  27.0  130.0  109.0  150.0
27   张智文    NaN  116.0  125.0  350.0  28.0  125.0  116.0  145.0
28    李季  114.0  117.0  118.0  349.0  29.0    NaN  117.0  138.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0  136.0  102.0    NaN
..   ...    ...    ...    ...    ...   ...    ...    ...    ...
38    艾宇  115.0  111.0  106.0  332.0  39.0    NaN  111.0  126.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0    NaN  112.0  126.0
40   邹建志   98.0  104.0  116.0  318.0  41.0    NaN  104.0  136.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0    NaN  103.0    NaN
42    孙波   96.0  130.0   89.0    NaN  43.0    NaN  130.0  109.0
43    张良  105.0  102.0  105.0    NaN  44.0    NaN  102.0  125.0
44   王春月  118.0   82.0  112.0  312.0  45.0    NaN   82.0  132.0
45   代明哲  101.0   91.0  115.0  307.0  46.0    NaN   91.0  135.0
46   张开羽  112.0   90.0  104.0  306.0  47.0    NaN   90.0  124.0
47   狄建译  109.0   68.0  126.0  303.0  48.0  126.0   68.0  146.0
48   张家硕  107.0   67.0  129.0    NaN  49.0  129.0   67.0  149.0
49    郭娜   94.0   98.0  104.0  296.0  50.0    NaN   98.0  124.0
50    周坤  107.0   76.0  104.0  287.0  51.0    NaN   76.0  124.0
51    洪禹  106.0  100.0   80.0  286.0  52.0    NaN  100.0  100.0
52   王治超  105.0   95.0   82.0  282.0  53.0    NaN   95.0  102.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0    NaN   59.0  128.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0    NaN   95.0  105.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0    NaN   71.0  105.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0    NaN   76.0   91.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0    NaN   87.0   64.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0    NaN   61.0   91.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0    NaN   77.0   63.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0    NaN   53.0   82.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0    NaN   49.0   84.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0    NaN   21.0   87.0
63    赵森   90.0   29.0   64.0  183.0  64.0    NaN   29.0   84.0
64   满朝升   78.0   45.0   47.0  170.0  65.0    NaN   45.0   67.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0    NaN   32.0   66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0    NaN   23.0   54.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0    NaN   23.0   54.0

[68 rows x 9 columns]

In [48]:
grade['英语加分']=grade.英语加分.fillna(150)

In [49]:
grade

      姓名     语文     数学     英语     总分   班名次   英语空值    数学1    数学2   英语加分
0     杨璐  131.0  143.0  144.0  418.0   1.0  144.0  143.0  143.0  150.0
1     王雪  131.0  135.0  144.0  410.0   2.0  144.0  135.0  135.0  150.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0  142.0  139.0  139.0  150.0
3    沙龙逸    0.0  148.0  136.0  407.0   4.0  136.0  148.0  148.0  150.0
4    李鉴学    0.0  135.0  140.0  401.0   5.0  140.0  135.0  135.0  150.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0  138.0  133.0  133.0  150.0
6     刘帅  116.0  143.0  140.0  399.0   7.0  140.0  143.0  143.0  150.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0  139.0  142.0  142.0  150.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0  135.0  139.0  139.0  150.0
9    林世博    0.0    NaN    NaN  387.0  10.0    NaN    0.0    NaN  150.0
10    张希    0.0  130.0  134.0  387.0  11.0  134.0  130.0  130.0  150.0
11    徐冲    0.0  124.0    NaN    NaN   NaN    NaN  124.0  124.0  150.0
12   苑宇飞    0.0  136.0  131.0  385.0  13.0  131.0  136.0  136.0  150.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0  139.0  123.0  123.0  150.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0  139.0  115.0  115.0  150.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0    NaN  127.0  127.0  150.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0  128.0  139.0  139.0  148.0
17   武传禹  119.0  129.0  130.0  378.0  18.0  130.0  129.0  129.0  150.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0  144.0  108.0  108.0  150.0
19    刘姗  124.0  128.0  122.0  374.0  20.0  122.0  128.0  128.0  142.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0  128.0  123.0  123.0  148.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0    NaN  131.0  131.0  150.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0  122.0  124.0  124.0  142.0
23   张曦月  116.0  123.0  119.0  358.0  24.0    NaN  123.0  123.0  139.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0    NaN  122.0  122.0  138.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0    NaN  126.0  126.0  131.0
26   赵殿宇    0.0  109.0  130.0  351.0  27.0  130.0  109.0  109.0  150.0
27   张智文    0.0  116.0  125.0  350.0  28.0  125.0  116.0  116.0  145.0
28    李季  114.0  117.0  118.0  349.0  29.0    NaN  117.0  117.0  138.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0  136.0  102.0  102.0  150.0
..   ...    ...    ...    ...    ...   ...    ...    ...    ...    ...
38    艾宇  115.0  111.0  106.0  332.0  39.0    NaN  111.0  111.0  126.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0    NaN  112.0  112.0  126.0
40   邹建志   98.0  104.0  116.0  318.0  41.0    NaN  104.0  104.0  136.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0    NaN  103.0    NaN  150.0
42    孙波   96.0  130.0   89.0    NaN  43.0    NaN  130.0  130.0  109.0
43    张良  105.0  102.0  105.0    NaN  44.0    NaN  102.0  102.0  125.0
44   王春月  118.0   82.0  112.0  312.0  45.0    NaN   82.0   82.0  132.0
45   代明哲  101.0   91.0  115.0  307.0  46.0    NaN   91.0   91.0  135.0
46   张开羽  112.0   90.0  104.0  306.0  47.0    NaN   90.0   90.0  124.0
47   狄建译  109.0   68.0  126.0  303.0  48.0  126.0   68.0   68.0  146.0
48   张家硕  107.0   67.0  129.0    NaN  49.0  129.0   67.0   67.0  149.0
49    郭娜   94.0   98.0  104.0  296.0  50.0    NaN   98.0   98.0  124.0
50    周坤  107.0   76.0  104.0  287.0  51.0    NaN   76.0   76.0  124.0
51    洪禹  106.0  100.0   80.0  286.0  52.0    NaN  100.0  100.0  100.0
52   王治超  105.0   95.0   82.0  282.0  53.0    NaN   95.0   95.0  102.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0    NaN   59.0   59.0  128.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0    NaN   95.0   95.0  105.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0    NaN   71.0   71.0  105.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0    NaN   76.0   76.0   91.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0    NaN   87.0   87.0   64.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0    NaN   61.0   61.0   91.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0    NaN   77.0   77.0   63.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0    NaN   53.0   53.0   82.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0    NaN   49.0   49.0   84.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0    NaN   21.0   21.0   87.0
63    赵森   90.0   29.0   64.0  183.0  64.0    NaN   29.0   29.0   84.0
64   满朝升   78.0   45.0   47.0  170.0  65.0    NaN   45.0   45.0   67.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0    NaN   32.0   32.0   66.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0    NaN   23.0   23.0   54.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0    NaN   23.0   23.0   54.0

[68 rows x 10 columns]

In [50]:
# combine 联合语文数学这两列，哪个分数高就保留哪个
grade['语文数学']=grade.语文.combine(grade.数学,lambda x1,x2:x1 if x1>x2 else x2)

In [51]:
grade

      姓名     语文     数学     英语     总分   班名次   英语空值    数学1    数学2   英语加分   语文数学
0     杨璐  131.0  143.0  144.0  418.0   1.0  144.0  143.0  143.0  150.0  143.0
1     王雪  131.0  135.0  144.0  410.0   2.0  144.0  135.0  135.0  150.0  135.0
2    韩林霖  127.0  139.0  142.0  408.0   3.0  142.0  139.0  139.0  150.0  139.0
3    沙龙逸    0.0  148.0  136.0  407.0   4.0  136.0  148.0  148.0  150.0  148.0
4    李鉴学    0.0  135.0  140.0  401.0   5.0  140.0  135.0  135.0  150.0  135.0
5    韩雨萌  129.0  133.0  138.0  400.0   6.0  138.0  133.0  133.0  150.0  133.0
6     刘帅  116.0  143.0  140.0  399.0   7.0  140.0  143.0  143.0  150.0  143.0
7    康惠雯  114.0  142.0  139.0  395.0   8.0  139.0  142.0  142.0  150.0  142.0
8    刘钰婷  115.0  139.0  135.0  389.0   9.0  135.0  139.0  139.0  150.0  139.0
9    林世博    0.0    NaN    NaN  387.0  10.0    NaN    0.0    NaN  150.0    NaN
10    张希    0.0  130.0  134.0  387.0  11.0  134.0  130.0  130.0  150.0  130.0
11    徐冲    0.0  124.0    NaN    NaN   NaN    NaN  124.0  124.0  150.0  124.0
12   苑宇飞    0.0  136.0  131.0  385.0  13.0  131.0  136.0  136.0  150.0  136.0
13   卢一凡  121.0  123.0  139.0  383.0  14.0  139.0  123.0  123.0  150.0  123.0
14   张瑞鑫  126.0  115.0  139.0  380.0  15.0  139.0  115.0  115.0  150.0  126.0
15   范作鑫  121.0  127.0    NaN    NaN  16.0    NaN  127.0  127.0  150.0  127.0
16   裴子翔  111.0  139.0  128.0  378.0  17.0  128.0  139.0  139.0  148.0  139.0
17   武传禹  119.0  129.0  130.0  378.0  18.0  130.0  129.0  129.0  150.0  129.0
18   任雪桐  124.0  108.0  144.0  376.0  19.0  144.0  108.0  108.0  150.0  124.0
19    刘姗  124.0  128.0  122.0  374.0  20.0  122.0  128.0  128.0  142.0  128.0
20   王柏坤  121.0  123.0  128.0  372.0  21.0  128.0  123.0  123.0  148.0  123.0
21   赵永刚  116.0  131.0    NaN  369.0  22.0    NaN  131.0  131.0  150.0  131.0
22  张馨月大  114.0  124.0  122.0  360.0  23.0  122.0  124.0  124.0  142.0  124.0
23   张曦月  116.0  123.0  119.0  358.0  24.0    NaN  123.0  123.0  139.0  123.0
24   胡丁文  116.0  122.0  118.0  356.0  25.0    NaN  122.0  122.0  138.0  122.0
25   赵美欣  118.0  126.0  111.0  355.0  26.0    NaN  126.0  126.0  131.0  126.0
26   赵殿宇    0.0  109.0  130.0  351.0  27.0  130.0  109.0  109.0  150.0  109.0
27   张智文    0.0  116.0  125.0  350.0  28.0  125.0  116.0  116.0  145.0  116.0
28    李季  114.0  117.0  118.0  349.0  29.0    NaN  117.0  117.0  138.0  117.0
29   杨加晖  110.0  102.0  136.0  348.0  30.0  136.0  102.0  102.0  150.0  110.0
..   ...    ...    ...    ...    ...   ...    ...    ...    ...    ...    ...
38    艾宇  115.0  111.0  106.0  332.0  39.0    NaN  111.0  111.0  126.0  115.0
39   黄俊焯  101.0  112.0  106.0  319.0  40.0    NaN  112.0  112.0  126.0  112.0
40   邹建志   98.0  104.0  116.0  318.0  41.0    NaN  104.0  104.0  136.0  104.0
41   张俊奎  103.0    NaN    NaN  317.0  42.0    NaN  103.0    NaN  150.0    NaN
42    孙波   96.0  130.0   89.0    NaN  43.0    NaN  130.0  130.0  109.0  130.0
43    张良  105.0  102.0  105.0    NaN  44.0    NaN  102.0  102.0  125.0  105.0
44   王春月  118.0   82.0  112.0  312.0  45.0    NaN   82.0   82.0  132.0  118.0
45   代明哲  101.0   91.0  115.0  307.0  46.0    NaN   91.0   91.0  135.0  101.0
46   张开羽  112.0   90.0  104.0  306.0  47.0    NaN   90.0   90.0  124.0  112.0
47   狄建译  109.0   68.0  126.0  303.0  48.0  126.0   68.0   68.0  146.0  109.0
48   张家硕  107.0   67.0  129.0    NaN  49.0  129.0   67.0   67.0  149.0  107.0
49    郭娜   94.0   98.0  104.0  296.0  50.0    NaN   98.0   98.0  124.0   98.0
50    周坤  107.0   76.0  104.0  287.0  51.0    NaN   76.0   76.0  124.0  107.0
51    洪禹  106.0  100.0   80.0  286.0  52.0    NaN  100.0  100.0  100.0  106.0
52   王治超  105.0   95.0   82.0  282.0  53.0    NaN   95.0   95.0  102.0  105.0
53   臧云飞  101.0   59.0  108.0  268.0  54.0    NaN   59.0   59.0  128.0  101.0
54   袁茂哲   85.0   95.0   85.0  265.0  55.0    NaN   95.0   95.0  105.0   95.0
55   丁婉艺   95.0   71.0   85.0  251.0  56.0    NaN   71.0   71.0  105.0   95.0
56   于娇莹   97.0   76.0   71.0  244.0  57.0    NaN   76.0   76.0   91.0   97.0
57   刘旭辉   99.0   87.0   44.0  230.0  58.0    NaN   87.0   87.0   64.0   99.0
58   张宇婷   83.0   61.0   71.0  215.0  59.0    NaN   61.0   61.0   91.0   83.0
59   黄明涛   87.0   77.0   43.0  207.0  60.0    NaN   77.0   77.0   63.0   87.0
60   吕文卓   82.0   53.0   62.0  197.0  61.0    NaN   53.0   53.0   82.0   82.0
61   王晟煜   79.0   49.0   64.0  192.0  62.0    NaN   49.0   49.0   84.0   79.0
62   孙龙基   99.0   21.0   67.0  187.0  63.0    NaN   21.0   21.0   87.0   99.0
63    赵森   90.0   29.0   64.0  183.0  64.0    NaN   29.0   29.0   84.0   90.0
64   满朝升   78.0   45.0   47.0  170.0  65.0    NaN   45.0   45.0   67.0   78.0
65   李忠浩   86.0   32.0   46.0  164.0  66.0    NaN   32.0   32.0   66.0   86.0
66   侯禹志   75.0   23.0   34.0  132.0  67.0    NaN   23.0   23.0   54.0   75.0
67   尹鸿涛   66.0   23.0   34.0  123.0  68.0    NaN   23.0   23.0   54.0   66.0

[68 rows x 11 columns]

### 文本处理

In [63]:
pd.set_option('max_columns',20)
pd.set_option('max_rows',500)
pd.set_option('max_colwidth',500)

In [37]:
movies=pd.read_csv('movie.csv',encoding='gbk',index_col=0)
movies.head(2)

,主演,5星,制片国家/地区,编剧,4星,类型,豆瓣评分,3星,上映日期,1星,2星,电影名称,片长
0,刘烨/冯远征/张嘉译/陈坤/马少骅/李沁/周润发/赵本山/黄磊/吕良伟/刘德华/廖凡/董洁/...,NaN,中国大陆 / 香港,董哲/郭俊立/黄建新,NaN,剧情/历史,NaN,NaN,2011/6/15,NaN,NaN,建党伟业,124分钟
1,希亚·拉博夫/罗茜·汉丁顿-惠特莉/乔什·杜哈明/泰瑞斯·吉布森/约翰·马尔科维奇/弗兰西斯...,12.80%,美国,伊伦·克鲁格,36.90%,动作/科幻,7.0,41.10%,2011/7/21,1.70%,7.50%,变形金刚3 Transformers: Dark of the Moon,154分钟

#### replace方法

In [29]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 13 columns):
主演         150 non-null object
5星         149 non-null object
制片国家/地区    150 non-null object
编剧         148 non-null object
4星         149 non-null object
类型         150 non-null object
豆瓣评分       149 non-null float64
3星         149 non-null object
上映日期       150 non-null object
1星         149 non-null object
2星         149 non-null object
电影名称       150 non-null object
片长         150 non-null object
dtypes: float64(1), object(12)
memory usage: 16.4+ KB

#### 常用字符串操作

In [33]:
movies.类型

0               剧情/历史
1               动作/科幻
2         喜剧/动作/动画/冒险
3            剧情/历史/战争
4            动作/武侠/古装
5            动作/奇幻/冒险
6         剧情/悬疑/奇幻/冒险
7               剧情/爱情
8         喜剧/动画/家庭/奇幻
9               动作/犯罪
10              动作/科幻
11        剧情/动作/悬疑/犯罪
12              剧情/动作
13        动作/爱情/奇幻/古装
14           剧情/动作/科幻
15              剧情/爱情
16           喜剧/动作/古装
17        剧情/动作/爱情/奇幻
18        剧情/动作/悬疑/武侠
19              喜剧/爱情
20        剧情/动作/传记/历史
21     剧情/动作/爱情/历史/古装
22              喜剧/动画
23        剧情/动作/科幻/运动
24           剧情/悬疑/惊悚
25              动作/科幻
26              喜剧/爱情
27              动作/奇幻
28           动作/战争/冒险
29           剧情/科幻/冒险
            ...
120          喜剧/动画/冒险
121    动作/爱情/悬疑/武侠/古装
122    动作/悬疑/惊悚/犯罪/冒险
123          动作/科幻/冒险
124             剧情/悬疑
125          喜剧/奇幻/冒险
126             动作/科幻
127             剧情/爱情
128                喜剧
129          动作/科幻/冒险
130       动作/悬疑/犯罪/古装
131                剧情
132          剧情/动作/犯罪
133             喜剧/爱情
134          剧情/喜剧/爱情
135          科幻/惊悚/灾难
136          动作/惊悚/犯罪
137          动作/科幻/冒险
138          喜剧/动画/冒险
139       动作/惊悚/犯罪/冒险
140          动作/科幻/冒险
141          科幻/惊悚/冒险
142          动作/奇幻/冒险
143             动作/冒险
144          动作/奇幻/冒险
145             动作/犯罪
146             动作/冒险
147          剧情/喜剧/爱情
148          剧情/动作/传记
149          喜剧/动作/犯罪
Name: 类型, Length: 150, dtype: object

In [35]:
# 统计字符出现的次数
movies.类型.str.count('/')

0      1
1      1
2      3
3      2
4      2
5      2
6      3
7      1
8      3
9      1
10     1
11     3
12     1
13     3
14     2
15     1
16     2
17     3
18     3
19     1
20     3
21     4
22     1
23     3
24     2
25     1
26     1
27     1
28     2
29     2
      ..
120    2
121    4
122    4
123    2
124    1
125    2
126    1
127    1
128    0
129    2
130    3
131    0
132    2
133    1
134    2
135    2
136    2
137    2
138    2
139    3
140    2
141    2
142    2
143    1
144    2
145    1
146    1
147    2
148    2
149    2
Name: 类型, Length: 150, dtype: int64

In [68]:
# 统计字符串的长度
movies.类型.str.len()

0       5
1       5
2      11
3       8
4       8
5       8
6      11
7       5
8      11
9       5
10      5
11     11
12      5
13     11
14      8
15      5
16      8
17     11
18     11
19      5
20     11
21     14
22      5
23     11
24      8
25      5
26      5
27      5
28      8
29      8
30      8
31      8
32      8
33      8
34      5
35      2
36      2
37      8
38      8
39      5
40      8
41      8
42     11
43      8
44      8
45      5
46     14
47     11
48      5
49      8
50      8
51      8
52     11
53      2
54     11
55      5
56      8
57      2
58      5
59     11
60      5
61      8
62      8
63      8
64      8
65      8
66      5
67      8
68      8
69      2
70      8
71      8
72      8
73      5
74      5
75      8
76      8
77      8
78      8
79      8
80      5
81      8
82      5
83      8
84     11
85      8
86      5
87      8
88      5
89     11
90      5
91     11
92      8
93      5
94      8
95      2
96      5
97     11
98      8
99      8
100     2
101     8
102    11
103    11
104    11
105     8
106     8
107     8
108     8
109     8
110    11
111    14
112     5
113     8
114    11
115    11
116     8
117     5
118     8
119     8
120     8
121    14
122    14
123     8
124     5
125     8
126     5
127     5
128     2
129     8
130    11
131     2
132     8
133     5
134     8
135     8
136     8
137     8
138     8
139    11
140     8
141     8
142     8
143     5
144     8
145     5
146     5
147     8
148     8
149     8
Name: 类型, dtype: int64

In [69]:
# 将每一行数据连接在一起
movies.类型.str.cat(sep='==>')

'剧情/历史==>动作/科幻==>喜剧/动作/动画/冒险==>剧情/历史/战争==>动作/武侠/古装==>动作/奇幻/冒险==>剧情/悬疑/奇幻/冒险==>剧情/爱情==>喜剧/动画/家庭/奇幻==>动作/犯罪==>动作/科幻==>剧情/动作/悬疑/犯罪==>剧情/动作==>动作/爱情/奇幻/古装==>剧情/动作/科幻==>剧情/爱情==>喜剧/动作/古装==>剧情/动作/爱情/奇幻==>剧情/动作/悬疑/武侠==>喜剧/爱情==>剧情/动作/传记/历史==>剧情/动作/爱情/历史/古装==>喜剧/动画==>剧情/动作/科幻/运动==>剧情/悬疑/惊悚==>动作/科幻==>喜剧/爱情==>动作/奇幻==>动作/战争/冒险==>剧情/科幻/冒险==>动作/科幻/冒险==>动作/科幻/冒险==>剧情/动作/科幻==>喜剧/家庭/儿童==>喜剧/爱情==>剧情==>爱情==>动作/科幻/冒险==>动作/科幻/冒险==>喜剧/动作==>喜剧/爱情/冒险==>剧情/喜剧/爱情==>动作/科幻/冒险/灾难==>动作/奇幻/冒险==>动作/惊悚/冒险==>剧情/爱情==>喜剧/动画/家庭/奇幻/冒险==>剧情/动作/惊悚/犯罪==>动作/科幻==>剧情/悬疑/恐怖==>动作/惊悚/犯罪==>喜剧/奇幻/古装==>剧情/动作/奇幻/冒险==>喜剧==>动作/科幻/奇幻/冒险==>喜剧/爱情==>动作/科幻/冒险==>喜剧==>喜剧/动作==>喜剧/动作/动画/奇幻==>剧情/犯罪==>动作/惊悚/冒险==>喜剧/动作/悬疑==>动作/奇幻/冒险==>动作/战争/古装==>动作/科幻/冒险==>剧情/冒险==>动作/惊悚/冒险==>动作/科幻/冒险==>喜剧==>动作/冒险/灾难==>剧情/科幻/冒险==>剧情/动作/犯罪==>动作/战争==>剧情/动画==>喜剧/爱情/奇幻==>喜剧/动画/冒险==>动作/奇幻/冒险==>动作/科幻/冒险==>喜剧/动作/奇幻==>动作/犯罪==>动作/奇幻/冒险==>喜剧/动作==>悬疑/奇幻/冒险==>喜剧/动作/动画/冒险==>剧情/奇幻/冒险==>喜剧/动作==>动作/科幻/冒险==>喜剧/爱情==>动作/科幻/奇幻/冒险==>喜剧/爱情==>剧情/动作/传记/历史==>动作/奇幻/冒险==>喜剧/动作==>剧情/动作/犯罪==>喜剧==>动作/冒险==>动作/科幻/奇幻/冒险==>剧情/动作/犯罪==>剧情/奇幻/冒险==>喜剧==>喜剧/动作/冒险==>剧情/爱情/惊悚/奇幻==>动作/惊悚/犯罪/冒险==>动作/科幻/奇幻/冒险==>剧情/奇幻/冒险==>剧情/爱情/灾难==>喜剧/动作/科幻==>喜剧/动画/冒险==>动作/科幻/冒险==>剧情/历史/战争/灾难==>剧情/动作/科幻/惊悚/犯罪==>动作/冒险==>动作/科幻/冒险==>动作/科幻/冒险/灾难==>动作/科幻/奇幻/冒险==>剧情/动作/犯罪==>剧情/悬疑==>科幻/惊悚/冒险==>动作/悬疑/惊悚==>喜剧/动画/冒险==>动作/爱情/悬疑/武侠/古装==>动作/悬疑/惊悚/犯罪/冒险==>动作/科幻/冒险==>剧情/悬疑==>喜剧/奇幻/冒险==>动作/科幻==>剧情/爱情==>喜剧==>动作/科幻/冒险==>动作/悬疑/犯罪/古装==>剧情==>剧情/动作/犯罪==>喜剧/爱情==>剧情/喜剧/爱情==>科幻/惊悚/灾难==>动作/惊悚/犯罪==>动作/科幻/冒险==>喜剧/动画/冒险==>动作/惊悚/犯罪/冒险==>动作/科幻/冒险==>科幻/惊悚/冒险==>动作/奇幻/冒险==>动作/冒险==>动作/奇幻/冒险==>动作/犯罪==>动作/冒险==>剧情/喜剧/爱情==>剧情/动作/传记==>喜剧/动作/犯罪'

In [71]:
# 将两列连接在一起
movies.电影名称.str.cat(movies['制片国家/地区'],sep='==>')

0                                                          建党伟业==>中国大陆 / 香港
1                                 变形金刚3 Transformers: Dark of the Moon==>美国
2                                                功夫熊猫2 Kung Fu Panda 2==>美国
3                                                         金陵十三钗==>中国大陆 / 香港
4                                                          龙门飞甲==>中国大陆 / 香港
5              加勒比海盗4：惊涛怪浪 Pirates of the Caribbean: On Stranger Tides==>美国
6      哈利·波特与死亡圣器(下) Harry Potter and the Deathly Hallows: Part 2==>美国 / 英国
7                                                              失恋33天==>中国大陆
8                                                 蓝精灵 The Smurfs==>美国 / 比利时
9                                                     速度与激情5 Fast Five==>美国
10                                           洛杉矶之战 Battle: Los Angeles==>美国
11                                                        窃听风云2==>香港 / 中国大陆
12                                                         新少林寺==>中国大陆 / 香港
13                                                              白蛇传说==>中国大陆
14                                 猩球崛起 Rise of the Planet of the Apes==>美国
15                                                           将爱情进行到底==>中国大陆
16                                                              武林外传==>中国大陆
17                                                           画壁==>中国大陆 / 香港
18                                                           武侠==>香港 / 中国大陆
19                                                         最强囍事==>中国大陆 / 香港
20                                                          关云长==>中国大陆 / 香港
21                                                        鸿门宴传奇==>中国大陆 / 香港
22                                                     喜羊羊与灰太狼之兔年顶呱呱==>中国大陆
23                                                铁甲钢拳 Real Steel==>美国 / 印度
24                                         致命伴旅 The Tourist==>美国 / 法国 / 意大利
25                   变形金刚4：绝迹重生 Transformers: Age of Extinction==>美国 / 中国大陆
26                                                              心花路放==>中国大陆
27                                                     西游记之大闹天宫==>中国大陆 / 香港
28                                                        智取威虎山==>中国大陆 / 香港
29                                   星际穿越 Interstellar==>美国 / 英国 / 加拿大 / 冰岛
30                            X战警：逆转未来 X-Men: Days of Future Past==>美国 / 英国
31                           美国队长2 Captain America: The Winter Soldier==>美国
32                           猩球崛起2：黎明之战 Dawn of the Planet of the Apes==>美国
33                                                             爸爸去哪儿==>中国大陆
34                                                              分手大师==>中国大陆
35                                                              后会无期==>中国大陆
36                                                              匆匆那年==>中国大陆
37                                  银河护卫队 Guardians of the Galaxy==>美国 / 英国
38                                     超凡蜘蛛侠2 The Amazing Spider-Man 2==>美国
39                                                    澳门风云 賭城風雲==>中国大陆 / 香港
40                                                    一步之遥==>中国大陆 / 美国 / 香港
41                                                    小时代3：刺金时代==>中国大陆 / 台湾
42                                                   哥斯拉 Godzilla==>美国 / 日本
43               霍比特人2：史矛革之战 The Hobbit: The Desolation of Smaug==>美国 / 新西兰
44                                         敢死队3 The Expendables 3==>美国 / 法国
45                                                              同桌的妳==>中国大陆
46                                    驯龙高手2 How to Train Your Dragon 2==>美国
47                                极品飞车 Need for Speed==>美国 / 菲律宾 / 爱尔兰 / 英国
48                                         明日边缘 Edge of Tomorrow==>美国 / 加拿大
49                                                             京城81号==>中国大陆
50                                        速度与激情7 Furious 7==>美国 / 中国大陆 / 日本
51                                                          捉妖记==>中国大陆 / 香港
52                                                          寻龙诀==>中国大陆 / 香港
53                                                                港囧==>中国大陆
54                                 复仇者联盟2：奥创纪元 Avengers: Age of Ultron==>美国
55                                                             夏洛特烦恼==>中国大陆
56                                         侏罗纪世界 Jurassic World==>美国 / 中国大陆
57                                                               煎饼侠==>中国大陆
58                                                 澳门风云2 賭城風雲II==>香港 / 中国大陆
59                                                          西游记之大圣归来==>中国大陆
60                                                               老炮儿==>中国大陆
61            碟中谍5：神秘国度 Mission: Impossible - Rogue Nation==>美国 / 香港 / 中国大陆
62                                                             唐人街探案==>中国大陆
63          霍比特人3：五军之战 The Hobbit: The Battle of the Five Armies==>美国 / 新西兰
64                                                         天将雄师==>中国大陆 / 香港
65                                          终结者：创世纪 Terminator Genisys==>美国
66                                                          狼图腾==>中国大陆 / 法国
67                                                              九层妖塔==>中国大陆
68                                                          蚁人 Ant-Man==>美国
69                                                              恶棍天使==>中国大陆
70                                             末日崩塌 San Andreas==>美国 / 澳大利亚
71                                               火星救援 The Martian==>美国 / 英国
72                                                    杀破狼2 殺破狼2==>香港 / 中国大陆
73                                                                战狼==>中国大陆
74                                         哆啦A梦：伴我同行 STAND BY ME ドラえもん==>日本
75                                                          美人鱼==>中国大陆 / 香港
76                                                      疯狂动物城 Zootopia==>美国
77                                       魔兽 Warcraft==>美国 / 中国大陆 / 加拿大 / 日本
78                                    美国队长3 Captain America: Civil War==>美国
79                                                 西游记之孙悟空三打白骨精==>中国大陆 / 香港
80                                                        湄公河行动==>中国大陆 / 香港
81                                            长城 The Great Wall==>中国大陆 / 美国
82                                                澳门风云3 賭城風雲III==>香港 / 中国大陆
83                                                              盗墓笔记==>中国大陆
84                                        功夫熊猫3 Kung Fu Panda 3==>美国 / 中国大陆
85                                                奇幻森林 The Jungle Book==>美国
86                                          绝地逃亡 Skiptrace==>中国大陆 / 美国 / 香港
87                             星球大战7：原力觉醒 Star Wars: The Force Awakens==>美国
88                                                          从你的全世界路过==>中国大陆
89                                            X战警：天启 X-Men: Apocalypse==>美国
90                                                 北京遇上西雅图之不二情书==>中国大陆 / 香港
91                                                          叶问3==>中国大陆 / 香港
92                                                 奇异博士 Doctor Strange==>美国
93                                                              铁道飞虎==>中国大陆
94                                                     寒战2 寒戰II==>中国大陆 / 香港
95                                                                情圣==>中国大陆
96                                             惊天魔盗团2 Now You See Me 2==>美国
97                     蝙蝠侠大战超人：正义黎明 Batman v Superman: Dawn of Justice==>美国
98                                                         使徒行者==>中国大陆 / 香港
99                神奇动物在哪里 Fantastic Beasts and Where to Find Them==>英国 / 美国
100                                                          人再囧途之泰囧==>中国大陆
101                                                        十二生肖==>中国大陆 / 香港
102                                                     画皮2 畫皮Ⅱ==>中国大陆 / 香港
103                          碟中谍4 Mission: Impossible - Ghost Protocol==>美国
104                                                 复仇者联盟 The Avengers==>美国
105                                少年派的奇幻漂流 Life of Pi==>美国 / 台湾 / 英国 / 加拿大
106                                               泰坦尼克号 3D版 Titanic 3D==>美国
107                                              黑衣人3 Men in Black III==>美国
108                                   冰川时代4 Ice Age: Continental Drift==>美国
109                        地心历险记2：神秘岛 Journey 2: The Mysterious Island==>美国
110                                                             一九四二==>中国大陆
111                              蝙蝠侠：黑暗骑士崛起 The Dark Knight Rises==>美国 / 英国
112                                             敢死队2 The Expendables 2==>美国
113                                       超凡蜘蛛侠 The Amazing Spider-Man==>美国
114                                                    超级战舰 Battleship==>美国
115                                                   异星战场 John Carter==>美国
116                                                       寒战 寒戰==>香港 / 中国大陆
117                                                         听风者==>中国大陆 / 香港
118                                              普罗米修斯 Prometheus==>美国 / 英国
119                                       谍影重重4 The Bourne Legacy==>美国 / 日本
120                          马达加斯加3 Madagascar 3: Europe's Most Wanted==>美国
121                                                        四大名捕==>中国大陆 / 香港
122                   大侦探福尔摩斯2：诡影游戏 Sherlock Holmes: A Game of Shadows==>美国
123                                              饥饿游戏 The Hunger Games==>美国
124                                                               搜索==>中国大陆
125                                                       西游降魔篇==>中国大陆 / 香港
126                                             钢铁侠3 Iron Man 3==>美国 / 中国大陆
127                                                       致我们终将逝去的青春==>中国大陆
128                                                             私人订制==>中国大陆
129                                                   环太平洋 Pacific Rim==>美国
130                                                    狄仁杰之神都龙王==>中国大陆 / 香港
131                                                       中国合伙人==>中国大陆 / 香港
132                                                    警察故事2013==>中国大陆 / 香港
133                                                     北京遇上西雅图==>中国大陆 / 香港
134                                                         小时代==>中国大陆 / 台湾
135                                                  地心引力 Gravity==>美国 / 英国
136                                                   速度与激情6 Furious 6==>美国
137                                          超人：钢铁之躯 Man of Steel==>美国 / 英国
138                                                   疯狂原始人 The Croods==>美国
139                                            007：大破天幕杀机 Skyfall==>英国 / 美国
140                                 星际迷航2：暗黑无界 Star Trek Into Darkness==>美国
141                                                侏罗纪公园 Jurassic Park==>美国
142                                      雷神2：黑暗世界 Thor: The Dark World==>美国
143                                   特种部队2：全面反击 G.I. Joe: Retaliation==>美国
144                 霍比特人1：意外之旅 The Hobbit: An Unexpected Journey==>美国 / 新西兰
145                                                       风暴 風暴==>香港 / 中国大陆
146                                                         天机·富春山居图==>中国大陆
147                                                   小时代2：青木时代==>中国大陆 / 台湾
148                                                   一代宗师 一代宗師==>中国大陆 / 香港
149                                                             不二神探==>中国大陆
Name: 电影名称, dtype: object

In [38]:
movies.类型.str.replace('/',' ')

0               剧情 历史
1               动作 科幻
2         喜剧 动作 动画 冒险
3            剧情 历史 战争
4            动作 武侠 古装
5            动作 奇幻 冒险
6         剧情 悬疑 奇幻 冒险
7               剧情 爱情
8         喜剧 动画 家庭 奇幻
9               动作 犯罪
10              动作 科幻
11        剧情 动作 悬疑 犯罪
12              剧情 动作
13        动作 爱情 奇幻 古装
14           剧情 动作 科幻
15              剧情 爱情
16           喜剧 动作 古装
17        剧情 动作 爱情 奇幻
18        剧情 动作 悬疑 武侠
19              喜剧 爱情
20        剧情 动作 传记 历史
21     剧情 动作 爱情 历史 古装
22              喜剧 动画
23        剧情 动作 科幻 运动
24           剧情 悬疑 惊悚
25              动作 科幻
26              喜剧 爱情
27              动作 奇幻
28           动作 战争 冒险
29           剧情 科幻 冒险
            ...
120          喜剧 动画 冒险
121    动作 爱情 悬疑 武侠 古装
122    动作 悬疑 惊悚 犯罪 冒险
123          动作 科幻 冒险
124             剧情 悬疑
125          喜剧 奇幻 冒险
126             动作 科幻
127             剧情 爱情
128                喜剧
129          动作 科幻 冒险
130       动作 悬疑 犯罪 古装
131                剧情
132          剧情 动作 犯罪
133             喜剧 爱情
134          剧情 喜剧 爱情
135          科幻 惊悚 灾难
136          动作 惊悚 犯罪
137          动作 科幻 冒险
138          喜剧 动画 冒险
139       动作 惊悚 犯罪 冒险
140          动作 科幻 冒险
141          科幻 惊悚 冒险
142          动作 奇幻 冒险
143             动作 冒险
144          动作 奇幻 冒险
145             动作 犯罪
146             动作 冒险
147          剧情 喜剧 爱情
148          剧情 动作 传记
149          喜剧 动作 犯罪
Name: 类型, Length: 150, dtype: object

#### 匹配字符串

In [79]:
# contains判断是否包含子串
movies[movies.主演.str.contains('刘烨')]

,主演,5星,制片国家/地区,编剧,4星,类型,豆瓣评分,3星,上映日期,1星,2星,电影名称,片长
0,刘烨/冯远征/张嘉译/陈坤/马少骅/李沁/周润发/赵本山/黄磊/吕良伟/刘德华/廖凡/董洁/周迅/范冰冰/张一山/王丹戎/李晨/黄轩/戚玉武/王学兵/周杰/王柏杰/董璇/叶璇/柳云龙/张家辉/范伟/方中信/冯巩/余少群/张涵予/李菁/陶泽如/侯勇/吴彦祖/王学圻/冯丹滢/徐峥/车永莉/王珞丹/陈道明/刘桦/井柏然/王力宏/刘佩琦/爱新觉罗·启星/韩庚/邓超/何平/李雪健/维塔斯/潘粤明/方力申/任达华/李湘/郭晓东/姜武/杨洋/郭涛/句号/杨颖/张震,NaN,中国大陆 / 香港,董哲/郭俊立/黄建新,NaN,剧情/历史,NaN,NaN,2011/6/15,NaN,NaN,建党伟业,124分钟
132,成龙/刘烨/景甜/殷桃/那威/刘仪伟/柳海龙/周晓鸥/于荣光/吴樾/刘佩琦/古力娜扎,4.80%,中国大陆 / 香港,丁晟,15.90%,剧情/动作/犯罪,5.7,47.40%,2013/12/24,8.20%,23.70%,警察故事2013,108分钟

In [80]:
movies[movies.主演.str.contains('刘德华')]

,主演,5星,制片国家/地区,编剧,4星,类型,豆瓣评分,3星,上映日期,1星,2星,电影名称,片长
0,刘烨/冯远征/张嘉译/陈坤/马少骅/李沁/周润发/赵本山/黄磊/吕良伟/刘德华/廖凡/董洁/周迅/范冰冰/张一山/王丹戎/李晨/黄轩/戚玉武/王学兵/周杰/王柏杰/董璇/叶璇/柳云龙/张家辉/范伟/方中信/冯巩/余少群/张涵予/李菁/陶泽如/侯勇/吴彦祖/王学圻/冯丹滢/徐峥/车永莉/王珞丹/陈道明/刘桦/井柏然/王力宏/刘佩琦/爱新觉罗·启星/韩庚/邓超/何平/李雪健/维塔斯/潘粤明/方力申/任达华/李湘/郭晓东/姜武/杨洋/郭涛/句号/杨颖/张震,NaN,中国大陆 / 香港,董哲/郭俊立/黄建新,NaN,剧情/历史,NaN,NaN,2011/6/15,NaN,NaN,建党伟业,124分钟
12,刘德华/谢霆锋/范冰冰/成龙/吴京/余少群/熊欣欣/于海/释彦能/白冰/景珂/岛田瑠那,4.10%,中国大陆 / 香港,袁锦麟/张志光/王秋雨/陈锦昌/张炭,17.00%,剧情/动作,5.9,51.80%,2011/1/19,5.50%,21.60%,新少林寺,132分钟
58,周润发/张家辉/刘嘉玲/余文乐/王诗龄/胡然/姜大卫/童菲/吴樾/金巧巧/黄德斌/姜皓文/曾国祥/袁泉/曾志伟/陈百祥/孟瑶/刘德华,4.70%,香港 / 中国大陆,王晶,15.90%,喜剧/动作,5.5,42.50%,2015/2/19,11.90%,25.00%,澳门风云2 賭城風雲II,110分钟
81,马特·达蒙/景甜/佩德罗·帕斯卡/刘德华/威廉·达福/张涵予/鹿晗/彭于晏/林更新/郑恺/黄轩/陈学冬/王俊凯/余心恬/刘冰/李亨/李京沐/纽曼·阿卡/约翰尼·希科/皮鲁·埃斯贝克,5.20%,中国大陆 / 美国,马克斯·布鲁克斯/爱德华·兹威克/马歇尔·赫斯科维兹/托尼·吉尔罗伊/托马斯·图尔,11.90%,动作/奇幻/冒险,4.9,32.80%,2016/12/16,26.50%,23.70%,长城 The Great Wall,104分钟
82,周润发/刘德华/张家辉/张学友/余文乐/李宇春/刘嘉玲/王诗龄/向佐/胡然/文咏珊/元秋/朴载相/童菲/罗家英/卢海鹏,3.20%,香港 / 中国大陆,王晶,5.00%,喜剧/动作,3.9,19.80%,2016/2/8,42.30%,29.80%,澳门风云3 賭城風雲III,112分钟
93,成龙/黄子韬/王凯/王大陆/徐帆/刘德华/张蓝心/吴永伦/桑平/房祖名/池内博之/那威/何云伟/浅野长英/矢野浩二/张艺上/高木贞佑,4.40%,中国大陆,丁晟/何可可,13.40%,喜剧/动作,5.1,38.20%,2016/12/23,20.70%,23.30%,铁道飞虎,124分钟
116,郭富城/梁家辉/李治廷/彭于晏/杨采妮/马伊琍/林家栋/安志杰/钱嘉乐/尹子维/王敏德 /黄芝琪/郑欣宜/文峰/贾晓晨/刘德华/何华超,12.90%,香港 / 中国大陆,梁乐民/陆剑青,48.80%,剧情/动作/犯罪,7.4,34.40%,2012/11/8,0.50%,3.40%,寒战 寒戰,103分钟
145,刘德华/姚晨/林家栋/胡军/吕良伟/姜皓文/黄德斌/梁烈唯/唐文龙/施祖男/尹子维/洪天照/王敏德 /王祖蓝/徐家杰/叶山豪/徐伟栋/张兆辉/陈保元/陈沛妍/黄智贤/卢海鹏/冼色丽,5.50%,香港 / 中国大陆,袁锦麟,26.00%,动作/犯罪,6.4,53.30%,2013/12/12,2.40%,12.60%,风暴 風暴,104分钟(中国大陆)
146,刘德华/林志玲/张静初/佟大为/斯琴高娃/奥马尔·本·哈依德/爱新觉罗·启星/石天琦/王曼妮/张光北,2.00%,中国大陆,孙健君,1.30%,动作/冒险,2.9,7.00%,2013/6/9,72.80%,16.90%,天机·富春山居图,122分钟

In [83]:
# startswith/endswith判断是否以某字符串开始/结尾
movies[movies['制片国家/地区'].str.startswith('香港')]

,主演,5星,制片国家/地区,编剧,4星,类型,豆瓣评分,3星,上映日期,1星,2星,电影名称,片长
11,古天乐/刘青云/吴彦祖/曾江/叶璇/黄奕/刘浩龙/胡枫/骆应钧/江毅/焦姣/郭锋/林迪安/邹凯光/方中信/钟均呈,13.90%,香港 / 中国大陆,麦兆辉/庄文强,51.50%,剧情/动作/悬疑/犯罪,7.5,31.80%,2011/8/18,0.30%,2.50%,窃听风云2,117分钟(中国大陆)
18,甄子丹/金城武/汤唯/王羽/惠英红/李小冉/姜武,6.10%,香港 / 中国大陆,林爱华,31.70%,剧情/动作/悬疑/武侠,6.6,49.60%,2011/7/4,2.10%,10.60%,武侠,115分钟
58,周润发/张家辉/刘嘉玲/余文乐/王诗龄/胡然/姜大卫/童菲/吴樾/金巧巧/黄德斌/姜皓文/曾国祥/袁泉/曾志伟/陈百祥/孟瑶/刘德华,4.70%,香港 / 中国大陆,王晶,15.90%,喜剧/动作,5.5,42.50%,2015/2/19,11.90%,25.00%,澳门风云2 賭城風雲II,110分钟
72,吴京/托尼·贾/张晋/任达华/卢惠光/恭硕良/林嘉华/蔡瀚亿/艾威/姜皓文/张驰/寇占文/古天乐/袁嘉敏,14.30%,香港 / 中国大陆,梁礼彦,44.80%,剧情/动作/犯罪,7.3,35.00%,2015/6/18,1.00%,4.80%,杀破狼2 殺破狼2,120分钟
82,周润发/刘德华/张家辉/张学友/余文乐/李宇春/刘嘉玲/王诗龄/向佐/胡然/文咏珊/元秋/朴载相/童菲/罗家英/卢海鹏,3.20%,香港 / 中国大陆,王晶,5.00%,喜剧/动作,3.9,19.80%,2016/2/8,42.30%,29.80%,澳门风云3 賭城風雲III,112分钟
116,郭富城/梁家辉/李治廷/彭于晏/杨采妮/马伊琍/林家栋/安志杰/钱嘉乐/尹子维/王敏德 /黄芝琪/郑欣宜/文峰/贾晓晨/刘德华/何华超,12.90%,香港 / 中国大陆,梁乐民/陆剑青,48.80%,剧情/动作/犯罪,7.4,34.40%,2012/11/8,0.50%,3.40%,寒战 寒戰,103分钟
145,刘德华/姚晨/林家栋/胡军/吕良伟/姜皓文/黄德斌/梁烈唯/唐文龙/施祖男/尹子维/洪天照/王敏德 /王祖蓝/徐家杰/叶山豪/徐伟栋/张兆辉/陈保元/陈沛妍/黄智贤/卢海鹏/冼色丽,5.50%,香港 / 中国大陆,袁锦麟,26.00%,动作/犯罪,6.4,53.30%,2013/12/12,2.40%,12.60%,风暴 風暴,104分钟(中国大陆)

In [84]:
movies[movies['制片国家/地区'].str.endswith('香港')]

,主演,5星,制片国家/地区,编剧,4星,类型,豆瓣评分,3星,上映日期,1星,2星,电影名称,片长
0,刘烨/冯远征/张嘉译/陈坤/马少骅/李沁/周润发/赵本山/黄磊/吕良伟/刘德华/廖凡/董洁/周迅/范冰冰/张一山/王丹戎/李晨/黄轩/戚玉武/王学兵/周杰/王柏杰/董璇/叶璇/柳云龙/张家辉/范伟/方中信/冯巩/余少群/张涵予/李菁/陶泽如/侯勇/吴彦祖/王学圻/冯丹滢/徐峥/车永莉/王珞丹/陈道明/刘桦/井柏然/王力宏/刘佩琦/爱新觉罗·启星/韩庚/邓超/何平/李雪健/维塔斯/潘粤明/方力申/任达华/李湘/郭晓东/姜武/杨洋/郭涛/句号/杨颖/张震,NaN,中国大陆 / 香港,董哲/郭俊立/黄建新,NaN,剧情/历史,NaN,NaN,2011/6/15,NaN,NaN,建党伟业,124分钟
3,克里斯蒂安·贝尔/倪妮/张歆怡/黄天元/韩熙庭/张逗逗/佟大为/曹可凡/渡部笃郎/黄海波/窦骁/聂远/高虎/秦昊/李玥敏/白雪/袁杨纯子/孙佳/朱良奇/小林成男/山中崇/保罗·施耐德/李纯/顾璇/周梦乔/周羽/邓莉/苏小妹/钱柳吟/叶清源 Qingyuan Ye/戴瑶君/沈俊然/李楚楚/金子欣/李瑞琦/谷艺璇/许佳丽/张照怡/王靖雯/谭逸敏/赵伊聪/来喜/奇道/王超北/王羽铮/李飞/王聪/项斌/郭晓明/涩谷天马/梶冈润一,29.00%,中国大陆 / 香港,刘恒/严歌苓,45.80%,剧情/历史/战争,8.0,21.10%,2011/12/15,1.20%,2.90%,金陵十三钗,145分钟
4,李连杰/周迅/陈坤/李宇春/桂纶镁/范晓萱/樊少皇/杜奕衡/刘家辉/张馨予/盛鉴/薛剑/王双宝/韩飞行/李炳渊/庄杰/吴迪/李军如/李思博/翟钢/吕德亮/戴明/周大庆/安琪儿/高杰/钢特木尔/张秋风/张东/白斯古楞/石占杰/石凯/卫博/沙学周/肖瑞/吴飞/张兆玉/张成林/吴正林,9.00%,中国大陆 / 香港,徐克/何冀平/朱雅欐,31.70%,动作/武侠/古装,6.7,46.30%,2011/12/15,2.40%,10.60%,龙门飞甲,120分钟
12,刘德华/谢霆锋/范冰冰/成龙/吴京/余少群/熊欣欣/于海/释彦能/白冰/景珂/岛田瑠那,4.10%,中国大陆 / 香港,袁锦麟/张志光/王秋雨/陈锦昌/张炭,17.00%,剧情/动作,5.9,51.80%,2011/1/19,5.50%,21.60%,新少林寺,132分钟
17,邓超/孙俪/闫妮/郑爽/柳岩/谢楠/邹兆龙/包贝尔/曾志伟/莫小棋/安志杰/包文婧/夏一瑶/蓝盈莹,2.50%,中国大陆 / 香港,陈嘉上,6.30%,剧情/动作/爱情/奇幻,4.4,29.00%,2011/9/29,26.90%,35.30%,画壁,122分钟
19,张柏芝/古天乐/甄子丹/刘嘉玲/黄百鸣/闫妮/熊黛林/杜汶泽/杨颖/汪圆圆/郑中基,1.90%,中国大陆 / 香港,黄百鸣/何妙祺,9.30%,喜剧/爱情,5.2,46.30%,2011/1/31,11.70%,30.80%,最强囍事,103分钟
20,甄子丹/姜文/孙俪/方中信/李宗翰/赵柯/王学兵/钱小豪/邵兵/董勇/王柏杰,2.20%,中国大陆 / 香港,麦兆辉/庄文强,8.10%,剧情/动作/传记/历史,4.9,38.10%,2011/4/26,16.50%,35.10%,关云长,110分钟
21,黎明/冯绍峰/刘亦菲/张涵予/黄秋生/陈小春/安志杰/贾青/孙文婷/孟瞳迪/黄姿琪/修庆/丁海峰/徐向东/陈观泰/午马/陈之辉/杜玉明,7.60%,中国大陆 / 香港,李仁港,26.50%,剧情/动作/爱情/历史/古装,6.3,45.20%,2011/11/29,5.30%,15.40%,鸿门宴传奇,135分钟
27,甄子丹/周润发/郭富城/何润东/海一天/夏梓桐/陈乔恩/陈慧琳/梁咏琪/张梓琳/郑家星/刘桦/张兆辉/罗仲谦/李菁/汪圆圆/梁雨恩,2.00%,中国大陆 / 香港,黄子桓/霍昕/司徒锦源/陈大利,4.90%,动作/奇幻,4.1,24.70%,2014/1/31,35.10%,33.30%,西游记之大闹天宫,119分钟
28,张涵予/梁家辉/林更新/余男/佟丽娅/韩庚/陈晓/谢苗/吴旭东/杜奕衡/海一天/张立/释彦能/孙蛟龙/程思寒/元武/肖轶/王尧/杨一威,19.60%,中国大陆 / 香港,黄建新/李杨/徐克/吴兵/董哲/林启安,49.20%,动作/战争/冒险,7.7,26.80%,2014/12/23,1.00%,3.30%,智取威虎山,141分钟
39,周润发/谢霆锋/杜汶泽/景甜/高虎/吴辰君/许绍雄/张晋/王敏德 /沈震轩/童菲/伍允龙,4.40%,中国大陆 / 香港,王晶,16.20%,喜剧/动作,5.6,45.50%,2014/1/31,10.00%,23.80%,澳门风云 賭城風雲,93分钟
40,姜文/葛优/周韵/舒淇/文章/王志文/洪晃/刘利年/那英/刘索拉/牛犇/姜洪齐/罗伯特·德尼罗/道格·佩尼卡斯,11.70%,中国大陆 / 美国 / 香港,姜文/郭俊立/王朔/廖一梅/述平/阎云飞/孙悦/孙睿/于彦琳,25.60%,喜剧/爱情/冒险,6.3,36.80%,2014/12/18,9.00%,17.00%,一步之遥,140分钟
51,白百何/井柏然/姜武/金燕玲/钟汉良/曾志伟/吴君如/汤唯/姚晨/闫妮/保剑锋/王栎鑫/郭晓东/李菁菁/田雨橙/张悦轩,11.60%,中国大陆 / 香港,袁锦麟,33.40%,喜剧/奇幻/古装,6.8,40.70%,2015/7/16,4.20%,10.10%,捉妖记,118分钟
52,陈坤/黄渤/舒淇/杨颖/夏雨/刘晓庆/颜卓灵/曹操/张东/黄西/僧格仁钦,19.50%,中国大陆 / 香港,张家鲁/天下霸唱,44.70%,剧情/动作/奇幻/冒险,7.5,29.50%,2015/12/18,1.40%,4.90%,寻龙诀,125分钟(中国大陆)
64,成龙/约翰·库萨克/艾德里安·布洛迪/崔始源/林鹏/王若心/肖央/王太利/洪天照/刘承俊/萝莉·佩斯特/冯绍峰/吴建豪/林嘉欣/沙妮·文森/西蒙子,5.80%,中国大陆 / 香港,李仁港,18.70%,动作/战争/古装,5.9,46.90%,2015/2/19,7.00%,21.50%,天将雄师,127分钟
75,邓超/罗志祥/张雨绮/林允/徐克/吴亦凡/李尚正/卢正雨/白客/孔连顺/田启文/文章/杨能/张美娥/李叶青/林子聪,14.50%,中国大陆 / 香港,周星驰/李思臻/何妙祺/曾瑾昌/卢正雨/江玉仪,30.60%,喜剧/爱情/奇幻,6.8,38.10%,2016/2/8,4.90%,11.90%,美人鱼,93分钟
79,郭富城/巩俐/冯绍峰/小沈阳/罗仲谦/费翔/陈慧琳/阿旺仁青/彭宇/程东/刘楚恬/余辛/魏璐/齐浠儿/母其弥雅/张籽沐,5.60%,中国大陆 / 香港,冉平/冉甲男/文宁,16.80%,喜剧/动作/奇幻,5.6,41.90%,2016/2/8,10.70%,25.00%,西游记之孙悟空三打白骨精,120分钟
80,张涵予/彭于晏/孙淳/陈宝国/冯文娟/刘显达/赵健/吴旭东/吴嘉龙/卢惠光/柏华力·莫高彼斯彻/维他亚·潘斯林加姆/战立国/石占杰/伍麟凯/Zobra/魏蔓/李佳璇/郝文婷/王笑龙/任蕊/Bhubhing Bhangsa-Ard/Achaya Vishwanath Govind/Nitidet Chery Junphli/Keerali Sivakuae/Alyaret Junamnoong/Vattcharachai Sunthomsin/Sarawut Kumsorn/Nongmal Bunchu/Subash A/L Sundaramoorthy/Itthiphon/Samrit Warin/纳卡琳·加汉/钟建龙/张敏嘉/陈沛兴/林美芬/詹姆斯·阿媞邦德/Amigo,28.50%,中国大陆 / 香港,林超贤/朱镜祺/刘小群/谭惠贞/林明杰,46.00%,动作/犯罪,8.0,22.10%,2016/9/30,0.70%,2.70%,湄公河行动,124分钟
86,成龙/范冰冰/约翰尼·诺克斯维尔/曾志伟/王敏德 /赵文瑄/伊芙·托雷斯/郭品超/施诗/延政勋/张蓝心/吉丽/托马尔·奥兹/保罗·菲利普·克拉克,5.00%,中国大陆 / 美国 / 香港,布莱恩·盖特伍德/本大卫·格拉宾斯基/杰·朗吉诺/亚历桑德罗·田中/成龙,13.80%,喜剧/动作,5.5,43.80%,2016/7/21,9.80%,27.50%,绝地逃亡 Skiptrace,111分钟(中国大陆)
90,汤唯/吴秀波/惠英红/秦沛/吴彦姝/颜卓灵/王志文/陆毅/祖锋/王茜/刘志宏/张一白/艾丽娅/李灿森/陈创/韩张,10.40%,中国大陆 / 香港,薛晓路/焦华静,26.90%,喜剧/爱情,6.5,42.30%,2016/4/29,4.40%,15.90%,北京遇上西雅图之不二情书,131分钟
91,甄子丹/迈克·泰森/张晋/熊黛林/谭耀文/吴千语/喻亢/郑则仕/梁家仁/张继聪/陈国坤/刘以达/宗菲/曹操/王实/崔璨/刘艺菲,6.90%,中国大陆 / 香港,黄子桓/陈大利/梁礼彦,24.00%,剧情/动作/传记/历史,6.3,51.00%,2016/3/4,3.20%,14.90%,叶问3,105分钟
94,郭富城/梁家辉/杨采妮/彭于晏/李治廷/文咏珊/周润发/马伊琍/杨祐宁/张国柱/吴樾/周笔畅/李子雄/骆应钧/林文龙,9.90%,中国大陆 / 香港,梁乐民/陆剑青/吴炜伦,37.00%,剧情/动作/犯罪,6.9,44.20%,2016/7/8,1.40%,7.40%,寒战2 寒戰II,110分钟
98,张家辉/古天乐/吴镇宇/佘诗曼/许绍雄/黄长兴/朱璇/梁琤/李光洁/张慧雯,10.30%,中国大陆 / 香港,关皓月,30.80%,剧情/动作/犯罪,6.7,44.30%,2016/8/11,2.50%,12.10%,使徒行者,109分钟
101,成龙/权相宇/廖凡/姚星彤/张蓝心/白露娜/刘承俊/吴彦祖/舒淇/李宗盛/陈柏霖/卢惠光/浅野长英/白冰/林鹏,9.00%,中国大陆 / 香港,成龙/唐季礼/邓景生/陈勋奇,30.80%,喜剧/动作/冒险,6.6,46.60%,2012/12/20,2.70%,10.90%,十二生肖,122分钟
102,周迅/赵薇/陈坤/冯绍峰/杨幂/费翔/陈廷嘉/鲁诺,4.70%,中国大陆 / 香港,冉平/冉甲男,18.00%,剧情/爱情/惊悚/奇幻,5.9,50.20%,2012/6/28,5.90%,21.20%,画皮2 畫皮Ⅱ,135分钟
117,梁朝伟/周迅/范晓萱/王学兵/董勇/甘婷婷/单立文,8.20%,中国大陆 / 香港,麦兆辉/庄文强/麦家,35.10%,剧情/悬疑,6.8,47.90%,2012/8/7,1.20%,7.70%,听风者,120分钟
121,邓超/刘亦菲/郑中基/邹兆龙/黄秋生/江一燕/吴秀波/邓萃雯/成泰燊/吴映洁/包贝尔/木幡龙/田启文/方安娜,2.70%,中国大陆 / 香港,温瑞安/陈嘉上/王思敏/谭广源,8.80%,动作/爱情/悬疑/武侠/古装,5.0,39.90%,2012/7/12,15.80%,32.90%,四大名捕,118分钟
125,文章/舒淇/黄渤/罗志祥/李尚正/陈炳强/赵志凌/周秀娜/杨迪/释彦能/冯勉恒/谢晶晶/何文辉/唐艺昕/卢正雨/张煜雯/葛行于/张超理/程思寒,14.90%,中国大陆 / 香港,周星驰/郭子健/霍昕/王芸/冯志强/卢正雨/李尚正/江玉仪,38.50%,喜剧/奇幻/冒险,7.1,35.80%,2013/2/10,2.70%,8.10%,西游降魔篇,110分钟
130,赵又廷/冯绍峰/林更新/金汎/杨颖/刘嘉玲/胡东/马京京/盛鉴/林朝绪/陈坤/言杰/汪汐潮,6.90%,中国大陆 / 香港,张家鲁/徐克/陈国富,30.00%,动作/悬疑/犯罪/古装,6.5,48.20%,2013/9/28,2.80%,12.20%,狄仁杰之神都龙王,133分钟
131,黄晓明/邓超/佟大为/杜鹃,19.20%,中国大陆 / 香港,周智勇/张冀/林爱华,47.10%,剧情,7.6,29.10%,2013/5/17,0.90%,3.60%,中国合伙人,112分钟
132,成龙/刘烨/景甜/殷桃/那威/刘仪伟/柳海龙/周晓鸥/于荣光/吴樾/刘佩琦/古力娜扎,4.80%,中国大陆 / 香港,丁晟,15.90%,剧情/动作/犯罪,5.7,47.40%,2013/12/24,8.20%,23.70%,警察故事2013,108分钟
133,汤唯/吴秀波/海清/宋美曼/宋美慧/金燕玲/买红妹/布拉德·哈德/李绮虹,16.40%,中国大陆 / 香港,薛晓路,43.00%,喜剧/爱情,7.4,34.30%,2013/3/21,1.30%,4.90%,北京遇上西雅图,123分钟
148,梁朝伟/章子怡/张震/宋慧乔/赵本山/小沈阳/王庆祥/张晋/卢海鹏/冯克安/刘家勇/张智霖/金士杰/徐锦江/刘洵/尚铁龙/罗莽/吴廷烨,26.60%,中国大陆 / 香港,邹静之/徐浩峰/王家卫,42.90%,剧情/动作/传记,7.8,24.80%,2013/1/8,1.40%,4.20%,一代宗师 一代宗師,111分钟(3D重映)

In [87]:
grade=pd.read_csv('./data/student_grade.txt',sep='\t')

In [88]:
grade[grade.姓名.str.startswith('王')]

     姓名   语文   数学   英语   总分  班名次
1    王雪  131  135  144  410    2
20  王柏坤  121  123  128  372   21
44  王春月  118   82  112  312   45
52  王治超  105   95   82  282   53
61  王晟煜   79   49   64  192   62

In [89]:
grade[grade.姓名.str.endswith('月')]

     姓名   语文   数学   英语   总分  班名次
23  张曦月  116  123  119  358   24
44  王春月  118   82  112  312   45

In [90]:
grade[grade.姓名.str.contains('月')]

      姓名   语文   数学   英语   总分  班名次
22  张馨月大  114  124  122  360   23
23   张曦月  116  123  119  358   24
36  张馨月小  108  110  119  337   37
44   王春月  118   82  112  312   45

### groupby分组

In [39]:
data={'学历':['初中','大学','初中','高中','高中','大学'],
      '测试成绩':[33,66,11,22,77,88],
     '产品评分':[3,5,1,2,4,2]}
df = pd.DataFrame(data=data)
df

   学历  测试成绩  产品评分
0  初中    33     3
1  大学    66     5
2  初中    11     1
3  高中    22     2
4  高中    77     4
5  大学    88     2

In [43]:
groups = df.groupby('学历')
groups

In [ ]:
groups.groups

In [96]:
groups.mean()

    测试成绩  产品评分
学历
初中  22.0   2.0
大学  77.0   3.5
高中  49.5   3.0

In [97]:
# 查看分了几组
groups.ngroups

3

In [98]:
# 查看分组的情况
groups.ngroup()

0    0
1    1
2    0
3    2
4    2
5    1
dtype: int64

In [99]:
# 对每一组数据进行统计值查看
df.groupby('学历').describe()

    产品评分                                            测试成绩                   \
   count mean       std  min   25%  50%   75%  max count  mean        std
学历
初中   2.0  2.0  1.414214  1.0  1.50  2.0  2.50  3.0   2.0  22.0  15.556349
大学   2.0  3.5  2.121320  2.0  2.75  3.5  4.25  5.0   2.0  77.0  15.556349
高中   2.0  3.0  1.414214  2.0  2.50  3.0  3.50  4.0   2.0  49.5  38.890873


     min    25%   50%    75%   max
学历
初中  11.0  16.50  22.0  27.50  33.0
大学  66.0  71.50  77.0  82.50  88.0
高中  22.0  35.75  49.5  63.25  77.0

#### 练习案例

In [101]:
drinks=pd.read_csv('./data/drinks.csv')
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [103]:
# 大陆进行分组
continent=drinks.groupby('continent')

In [104]:
# 统计大陆平均消耗啤酒量?
continent.beer_servings.mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

In [105]:
drinks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
country                         193 non-null object
beer_servings                   193 non-null int64
spirit_servings                 193 non-null int64
wine_servings                   193 non-null int64
total_litres_of_pure_alcohol    193 non-null float64
continent                       170 non-null object
dtypes: float64(1), int64(3), object(2)
memory usage: 9.1+ KB

In [108]:
drinks.continent.value_counts(dropna=False)

AF    53
EU    45
AS    44
NA    23
OC    16
SA    12
Name: continent, dtype: int64

In [107]:
# 填补成'NA'
drinks.continent.fillna('NA',inplace=True)

#### agg聚合统计

In [44]:
groups.groups

{'初中': Int64Index([0, 2], dtype='int64'),
 '大学': Int64Index([1, 5], dtype='int64'),
 '高中': Int64Index([3, 4], dtype='int64')}

In [109]:
groups.mean()

    测试成绩  产品评分
学历
初中  22.0   2.0
大学  77.0   3.5
高中  49.5   3.0

In [110]:
groups.agg('mean')

    测试成绩  产品评分
学历
初中  22.0   2.0
大学  77.0   3.5
高中  49.5   3.0

In [111]:
groups.agg(['max','min','median'])

   测试成绩            产品评分
    max min median  max min median
学历
初中   33  11   22.0    3   1    2.0
大学   88  66   77.0    5   2    3.5
高中   77  22   49.5    4   2    3.0

In [112]:
groups.agg({'测试成绩':['std','sum'],'产品评分':['var','median']})

         测试成绩      产品评分
          std  sum  var median
学历
初中  15.556349   44  2.0    2.0
大学  15.556349  154  4.5    3.5
高中  38.890873   99  2.0    3.0

In [113]:
groups.agg(lambda x:x.max()-x.min())

    测试成绩  产品评分
学历
初中    22     2
大学    22     3
高中    55     2

#### 筛选列

In [45]:
groups.mean()['测试成绩']

学历
初中    22.0
大学    77.0
高中    49.5
Name: 测试成绩, dtype: float64

In [46]:
df.groupby('学历')['测试成绩'].mean()

学历
初中    22.0
大学    77.0
高中    49.5
Name: 测试成绩, dtype: float64

#### 练习

In [119]:
index = ['蜘蛛侠', '灭霸', '奇异博士', '钢铁侠','蝙蝠侠', '索尔' ]
data = {
    "城市":["纽约皇后区", "泰坦星球","费城", "纽约", "哥谭",  "阿斯加德" ],
    "年龄":[19, 3000, 30, 37, 40, 1500],
}
user_info = pd.DataFrame(data=data,index=index )

In [121]:
# 索引名称
user_info.index.name='英雄姓名'

In [123]:
# 新增一列性别
user_info['性别']='男'

In [125]:
# 新增行
user_info.loc['黑寡妇']=['前苏联',27,'女']

In [127]:
user_info.loc['神奇女侠']=['岛屿',24,'女']

In [128]:
user_info

         城市    年龄 性别
英雄姓名
蜘蛛侠   纽约皇后区    19  男
灭霸     泰坦星球  3000  男
奇异博士     费城    30  男
钢铁侠      纽约    37  男
蝙蝠侠      哥谭    40  男
索尔     阿斯加德  1500  男
黑寡妇     前苏联    27  女
神奇女侠     岛屿    24  女

In [129]:
# 新增一列‘中青年’,年龄大于35是中年，小于35是青年
user_info['中青年']=np.where(user_info.年龄>35,'中年','青年')

In [130]:
user_info

         城市    年龄 性别 中青年
英雄姓名
蜘蛛侠   纽约皇后区    19  男  青年
灭霸     泰坦星球  3000  男  中年
奇异博士     费城    30  男  青年
钢铁侠      纽约    37  男  中年
蝙蝠侠      哥谭    40  男  中年
索尔     阿斯加德  1500  男  中年
黑寡妇     前苏联    27  女  青年
神奇女侠     岛屿    24  女  青年

In [131]:
planet = {
"纽约皇后区": "地球人",
"泰坦星球": "外星人",
"费城": "地球人",
"纽约": "地球人", 
"哥谭":"地球人", 
"阿斯加德":"外星人", 
"前苏联":"地球人",
"岛屿":"地球人"
}

In [133]:
user_info['星球']=user_info.城市.map(planet)

In [134]:
user_info

         城市    年龄 性别 中青年   星球
英雄姓名
蜘蛛侠   纽约皇后区    19  男  青年  地球人
灭霸     泰坦星球  3000  男  中年  外星人
奇异博士     费城    30  男  青年  地球人
钢铁侠      纽约    37  男  中年  地球人
蝙蝠侠      哥谭    40  男  中年  地球人
索尔     阿斯加德  1500  男  中年  外星人
黑寡妇     前苏联    27  女  青年  地球人
神奇女侠     岛屿    24  女  青年  地球人

In [135]:
# 将地球人替换成Human，将外星人替换成Alien，新增一列
def translate(x):
    if x=='地球人':
        return 'Human'
    elif x=='外星人':
        return 'Alien'

In [136]:
user_info['种族'] = user_info.星球.map(translate)
user_info

         城市    年龄 性别 中青年   星球     种族
英雄姓名
蜘蛛侠   纽约皇后区    19  男  青年  地球人  Human
灭霸     泰坦星球  3000  男  中年  外星人  Alien
奇异博士     费城    30  男  青年  地球人  Human
钢铁侠      纽约    37  男  中年  地球人  Human
蝙蝠侠      哥谭    40  男  中年  地球人  Human
索尔     阿斯加德  1500  男  中年  外星人  Alien
黑寡妇     前苏联    27  女  青年  地球人  Human
神奇女侠     岛屿    24  女  青年  地球人  Human

In [137]:
# 新增一列‘年不年轻’，大于50的返回中年，小于50返回还年轻
user_info['年不年轻']=user_info.年龄.apply(lambda x:'中年' if x>50 else '还年轻')
user_info

         城市    年龄 性别 中青年   星球     种族 年不年轻
英雄姓名
蜘蛛侠   纽约皇后区    19  男  青年  地球人  Human  还年轻
灭霸     泰坦星球  3000  男  中年  外星人  Alien   中年
奇异博士     费城    30  男  青年  地球人  Human  还年轻
钢铁侠      纽约    37  男  中年  地球人  Human  还年轻
蝙蝠侠      哥谭    40  男  中年  地球人  Human  还年轻
索尔     阿斯加德  1500  男  中年  外星人  Alien   中年
黑寡妇     前苏联    27  女  青年  地球人  Human  还年轻
神奇女侠     岛屿    24  女  青年  地球人  Human  还年轻

In [138]:
user_info['身高']=[175,270,178,'NaN',180,'NaN',168,'NaN']

In [139]:
user_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 蜘蛛侠 to 神奇女侠
Data columns (total 8 columns):
城市      8 non-null object
年龄      8 non-null int64
性别      8 non-null object
中青年     8 non-null object
星球      8 non-null object
种族      8 non-null object
年不年轻    8 non-null object
身高      8 non-null object
dtypes: int64(1), object(7)
memory usage: 896.0+ bytes

In [143]:
# 身高加上cm单位
user_info['身高']=user_info.身高.map(lambda x:str(x) if str(x)=='NaN' else str(x)+'cm')

In [144]:
user_info

         城市    年龄 性别 中青年   星球     种族 年不年轻     身高
英雄姓名
蜘蛛侠   纽约皇后区    19  男  青年  地球人  Human  还年轻  175cm
灭霸     泰坦星球  3000  男  中年  外星人  Alien   中年  270cm
奇异博士     费城    30  男  青年  地球人  Human  还年轻  178cm
钢铁侠      纽约    37  男  中年  地球人  Human  还年轻    NaN
蝙蝠侠      哥谭    40  男  中年  地球人  Human  还年轻  180cm
索尔     阿斯加德  1500  男  中年  外星人  Alien   中年    NaN
黑寡妇     前苏联    27  女  青年  地球人  Human  还年轻  168cm
神奇女侠     岛屿    24  女  青年  地球人  Human  还年轻    NaN

In [145]:
# 删除cm
user_info.身高=user_info.身高.str.replace('cm','')

In [149]:
user_info.性别=user_info.性别.str.replace('男','0')

In [150]:
user_info.性别=user_info.性别.str.replace('女','1')

In [153]:
user_info.性别=user_info.性别.astype('int')

In [154]:
user_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 蜘蛛侠 to 神奇女侠
Data columns (total 8 columns):
城市      8 non-null object
年龄      8 non-null int64
性别      8 non-null int32
中青年     8 non-null object
星球      8 non-null object
种族      8 non-null object
年不年轻    8 non-null object
身高      8 non-null object
dtypes: int32(1), int64(1), object(6)
memory usage: 864.0+ bytes

In [156]:
user_info=user_info.reset_index()

In [157]:
user_info

   英雄姓名     城市    年龄  性别 中青年   星球     种族 年不年轻   身高
0   蜘蛛侠  纽约皇后区    19   0  青年  地球人  Human  还年轻  175
1    灭霸   泰坦星球  3000   0  中年  外星人  Alien   中年  270
2  奇异博士     费城    30   0  青年  地球人  Human  还年轻  178
3   钢铁侠     纽约    37   0  中年  地球人  Human  还年轻  NaN
4   蝙蝠侠     哥谭    40   0  中年  地球人  Human  还年轻  180
5    索尔   阿斯加德  1500   0  中年  外星人  Alien   中年  NaN
6   黑寡妇    前苏联    27   1  青年  地球人  Human  还年轻  168
7  神奇女侠     岛屿    24   1  青年  地球人  Human  还年轻  NaN

In [161]:
user_info['A']=user_info.年不年轻.str.split('年')

In [160]:
user_info.年不年轻.str.partition('年')

   0  1  2
0  还  年  轻
1  中  年
2  还  年  轻
3  还  年  轻
4  还  年  轻
5  中  年
6  还  年  轻
7  还  年  轻

In [167]:
user_info.A[0][1]

'轻'