### 离散化

#### 等距分箱

In [1]:
import numpy as np
import pandas as pd

In [4]:
grade = pd.read_csv('student_grade.txt',sep='\t')
grade.head()

    姓名   语文   数学   英语   总分  班名次
0   杨璐  131  143  144  418    1
1   王雪  131  135  144  410    2
2  韩林霖  127  139  142  408    3
3  沙龙逸  123  148  136  407    4
4  李鉴学  126  135  140  401    5

In [3]:
pd.cut(grade.数学,3)

0      (105.667, 148.0]
1      (105.667, 148.0]
2      (105.667, 148.0]
3      (105.667, 148.0]
4      (105.667, 148.0]
5      (105.667, 148.0]
6      (105.667, 148.0]
7      (105.667, 148.0]
8      (105.667, 148.0]
9      (105.667, 148.0]
10     (105.667, 148.0]
11     (105.667, 148.0]
12     (105.667, 148.0]
13     (105.667, 148.0]
14     (105.667, 148.0]
15     (105.667, 148.0]
16     (105.667, 148.0]
17     (105.667, 148.0]
18     (105.667, 148.0]
19     (105.667, 148.0]
20     (105.667, 148.0]
21     (105.667, 148.0]
22     (105.667, 148.0]
23     (105.667, 148.0]
24     (105.667, 148.0]
25     (105.667, 148.0]
26     (105.667, 148.0]
27     (105.667, 148.0]
28     (105.667, 148.0]
29    (63.333, 105.667]
            ...
38     (105.667, 148.0]
39     (105.667, 148.0]
40    (63.333, 105.667]
41    (63.333, 105.667]
42     (105.667, 148.0]
43    (63.333, 105.667]
44    (63.333, 105.667]
45    (63.333, 105.667]
46    (63.333, 105.667]
47    (63.333, 105.667]
48    (63.333, 105.667]
49    (63.333, 105.667]
50    (63.333, 105.667]
51    (63.333, 105.667]
52    (63.333, 105.667]
53     (20.873, 63.333]
54    (63.333, 105.667]
55    (63.333, 105.667]
56    (63.333, 105.667]
57    (63.333, 105.667]
58     (20.873, 63.333]
59    (63.333, 105.667]
60     (20.873, 63.333]
61     (20.873, 63.333]
62     (20.873, 63.333]
63     (20.873, 63.333]
64     (20.873, 63.333]
65     (20.873, 63.333]
66     (20.873, 63.333]
67     (20.873, 63.333]
Name: 数学, Length: 68, dtype: category
Categories (3, interval[float64]): [(20.873, 63.333] < (63.333, 105.667] < (105.667, 148.0]]

In [4]:
pd.cut(grade.数学,3,labels=['低分','中等分','高分']) # 定义箱子的名称

0      高分
1      高分
2      高分
3      高分
4      高分
5      高分
6      高分
7      高分
8      高分
9      高分
10     高分
11     高分
12     高分
13     高分
14     高分
15     高分
16     高分
17     高分
18     高分
19     高分
20     高分
21     高分
22     高分
23     高分
24     高分
25     高分
26     高分
27     高分
28     高分
29    中等分
     ...
38     高分
39     高分
40    中等分
41    中等分
42     高分
43    中等分
44    中等分
45    中等分
46    中等分
47    中等分
48    中等分
49    中等分
50    中等分
51    中等分
52    中等分
53     低分
54    中等分
55    中等分
56    中等分
57    中等分
58     低分
59    中等分
60     低分
61     低分
62     低分
63     低分
64     低分
65     低分
66     低分
67     低分
Name: 数学, Length: 68, dtype: category
Categories (3, object): [低分 < 中等分 < 高分]

In [5]:
pd.cut(grade.数学,3,right=False)

0     [105.667, 148.127)
1     [105.667, 148.127)
2     [105.667, 148.127)
3     [105.667, 148.127)
4     [105.667, 148.127)
5     [105.667, 148.127)
6     [105.667, 148.127)
7     [105.667, 148.127)
8     [105.667, 148.127)
9     [105.667, 148.127)
10    [105.667, 148.127)
11    [105.667, 148.127)
12    [105.667, 148.127)
13    [105.667, 148.127)
14    [105.667, 148.127)
15    [105.667, 148.127)
16    [105.667, 148.127)
17    [105.667, 148.127)
18    [105.667, 148.127)
19    [105.667, 148.127)
20    [105.667, 148.127)
21    [105.667, 148.127)
22    [105.667, 148.127)
23    [105.667, 148.127)
24    [105.667, 148.127)
25    [105.667, 148.127)
26    [105.667, 148.127)
27    [105.667, 148.127)
28    [105.667, 148.127)
29     [63.333, 105.667)
             ...
38    [105.667, 148.127)
39    [105.667, 148.127)
40     [63.333, 105.667)
41     [63.333, 105.667)
42    [105.667, 148.127)
43     [63.333, 105.667)
44     [63.333, 105.667)
45     [63.333, 105.667)
46     [63.333, 105.667)
47     [63.333, 105.667)
48     [63.333, 105.667)
49     [63.333, 105.667)
50     [63.333, 105.667)
51     [63.333, 105.667)
52     [63.333, 105.667)
53        [21.0, 63.333)
54     [63.333, 105.667)
55     [63.333, 105.667)
56     [63.333, 105.667)
57     [63.333, 105.667)
58        [21.0, 63.333)
59     [63.333, 105.667)
60        [21.0, 63.333)
61        [21.0, 63.333)
62        [21.0, 63.333)
63        [21.0, 63.333)
64        [21.0, 63.333)
65        [21.0, 63.333)
66        [21.0, 63.333)
67        [21.0, 63.333)
Name: 数学, Length: 68, dtype: category
Categories (3, interval[float64]): [[21.0, 63.333) < [63.333, 105.667) < [105.667, 148.127)]

优秀 135-150
良好 120-135
及格 90-120
不及格 0-90

In [7]:
pd.cut(grade.数学,bins=[0,90,120,135,150],right=False)

0     [135, 150)
1     [135, 150)
2     [135, 150)
3     [135, 150)
4     [135, 150)
5     [120, 135)
6     [135, 150)
7     [135, 150)
8     [135, 150)
9     [135, 150)
10    [120, 135)
11    [120, 135)
12    [135, 150)
13    [120, 135)
14     [90, 120)
15    [120, 135)
16    [135, 150)
17    [120, 135)
18     [90, 120)
19    [120, 135)
20    [120, 135)
21    [120, 135)
22    [120, 135)
23    [120, 135)
24    [120, 135)
25    [120, 135)
26     [90, 120)
27     [90, 120)
28     [90, 120)
29     [90, 120)
         ...
38     [90, 120)
39     [90, 120)
40     [90, 120)
41     [90, 120)
42    [120, 135)
43     [90, 120)
44       [0, 90)
45     [90, 120)
46     [90, 120)
47       [0, 90)
48       [0, 90)
49     [90, 120)
50       [0, 90)
51     [90, 120)
52     [90, 120)
53       [0, 90)
54     [90, 120)
55       [0, 90)
56       [0, 90)
57       [0, 90)
58       [0, 90)
59       [0, 90)
60       [0, 90)
61       [0, 90)
62       [0, 90)
63       [0, 90)
64       [0, 90)
65       [0, 90)
66       [0, 90)
67       [0, 90)
Name: 数学, Length: 68, dtype: category
Categories (4, interval[int64]): [[0, 90) < [90, 120) < [120, 135) < [135, 150)]

In [8]:
pd.cut(grade.数学,bins=[0,90,120,135,151],right=False,
       labels=['不及格','及格','良好','优秀'],retbins=True)

(0      优秀
 1      优秀
 2      优秀
 3      优秀
 4      优秀
 5      良好
 6      优秀
 7      优秀
 8      优秀
 9      优秀
 10     良好
 11     良好
 12     优秀
 13     良好
 14     及格
 15     良好
 16     优秀
 17     良好
 18     及格
 19     良好
 20     良好
 21     良好
 22     良好
 23     良好
 24     良好
 25     良好
 26     及格
 27     及格
 28     及格
 29     及格
      ...
 38     及格
 39     及格
 40     及格
 41     及格
 42     良好
 43     及格
 44    不及格
 45     及格
 46     及格
 47    不及格
 48    不及格
 49     及格
 50    不及格
 51     及格
 52     及格
 53    不及格
 54     及格
 55    不及格
 56    不及格
 57    不及格
 58    不及格
 59    不及格
 60    不及格
 61    不及格
 62    不及格
 63    不及格
 64    不及格
 65    不及格
 66    不及格
 67    不及格
 Name: 数学, Length: 68, dtype: category
 Categories (4, object): [不及格 < 及格 < 良好 < 优秀],
 array([  0,  90, 120, 135, 151]))

In [9]:
grade['数学离散化']=pd.cut(grade.数学,bins=[0,90,120,135,151],right=False,
       labels=['不及格','及格','良好','优秀'])

In [10]:
grade.head()

    姓名   语文   数学   英语   总分  班名次 数学离散化
0   杨璐  131  143  144  418    1    优秀
1   王雪  131  135  144  410    2    优秀
2  韩林霖  127  139  142  408    3    优秀
3  沙龙逸  123  148  136  407    4    优秀
4  李鉴学  126  135  140  401    5    优秀

练习：总分离散化
0-200  不及格
200-300  及格
300-400  良好
400-450  优秀

In [11]:
grade['总分离散化'] = pd.cut(grade.总分,bins=[0,200,300,400,450],
                       labels=['不及格','及格','良好','优秀'])
grade.head()

    姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化
0   杨璐  131  143  144  418    1    优秀    优秀
1   王雪  131  135  144  410    2    优秀    优秀
2  韩林霖  127  139  142  408    3    优秀    优秀
3  沙龙逸  123  148  136  407    4    优秀    优秀
4  李鉴学  126  135  140  401    5    优秀    优秀

In [12]:
grade.数学离散化.value_counts()

及格     23
不及格    18
良好     16
优秀     11
Name: 数学离散化, dtype: int64

#### 等深分箱

In [13]:
pd.qcut(grade.数学,4)

0     (127.25, 148.0]
1     (127.25, 148.0]
2     (127.25, 148.0]
3     (127.25, 148.0]
4     (127.25, 148.0]
5     (127.25, 148.0]
6     (127.25, 148.0]
7     (127.25, 148.0]
8     (127.25, 148.0]
9     (127.25, 148.0]
10    (127.25, 148.0]
11    (111.5, 127.25]
12    (127.25, 148.0]
13    (111.5, 127.25]
14    (111.5, 127.25]
15    (111.5, 127.25]
16    (127.25, 148.0]
17    (127.25, 148.0]
18     (85.75, 111.5]
19    (127.25, 148.0]
20    (111.5, 127.25]
21    (127.25, 148.0]
22    (111.5, 127.25]
23    (111.5, 127.25]
24    (111.5, 127.25]
25    (111.5, 127.25]
26     (85.75, 111.5]
27    (111.5, 127.25]
28    (111.5, 127.25]
29     (85.75, 111.5]
           ...
38     (85.75, 111.5]
39    (111.5, 127.25]
40     (85.75, 111.5]
41     (85.75, 111.5]
42    (127.25, 148.0]
43     (85.75, 111.5]
44    (20.999, 85.75]
45     (85.75, 111.5]
46     (85.75, 111.5]
47    (20.999, 85.75]
48    (20.999, 85.75]
49     (85.75, 111.5]
50    (20.999, 85.75]
51     (85.75, 111.5]
52     (85.75, 111.5]
53    (20.999, 85.75]
54     (85.75, 111.5]
55    (20.999, 85.75]
56    (20.999, 85.75]
57     (85.75, 111.5]
58    (20.999, 85.75]
59    (20.999, 85.75]
60    (20.999, 85.75]
61    (20.999, 85.75]
62    (20.999, 85.75]
63    (20.999, 85.75]
64    (20.999, 85.75]
65    (20.999, 85.75]
66    (20.999, 85.75]
67    (20.999, 85.75]
Name: 数学, Length: 68, dtype: category
Categories (4, interval[float64]): [(20.999, 85.75] < (85.75, 111.5] < (111.5, 127.25] < (127.25, 148.0]]

In [15]:
grade['数学等深']=pd.qcut(grade.数学,4,labels=['低分','较低','较高','高分'])

In [16]:
grade.数学等深.value_counts()

高分    17
较高    17
较低    17
低分    17
Name: 数学等深, dtype: int64

#### 排序

1.按值排序

In [18]:
grade.head()

    姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深
0   杨璐  131  143  144  418    1    优秀    优秀   高分
1   王雪  131  135  144  410    2    优秀    优秀   高分
2  韩林霖  127  139  142  408    3    优秀    优秀   高分
3  沙龙逸  123  148  136  407    4    优秀    优秀   高分
4  李鉴学  126  135  140  401    5    优秀    优秀   高分

In [19]:
grade.sort_values('语文')

      姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深
67   尹鸿涛   66   23   34  123   68   不及格   不及格   低分
66   侯禹志   75   23   34  132   67   不及格   不及格   低分
64   满朝升   78   45   47  170   65   不及格   不及格   低分
61   王晟煜   79   49   64  192   62   不及格   不及格   低分
60   吕文卓   82   53   62  197   61   不及格   不及格   低分
58   张宇婷   83   61   71  215   59   不及格    及格   低分
54   袁茂哲   85   95   85  265   55    及格    及格   较低
65   李忠浩   86   32   46  164   66   不及格   不及格   低分
59   黄明涛   87   77   43  207   60   不及格    及格   低分
63    赵森   90   29   64  183   64   不及格   不及格   低分
49    郭娜   94   98  104  296   50    及格    及格   较低
55   丁婉艺   95   71   85  251   56   不及格    及格   低分
42    孙波   96  130   89  315   43    良好    良好   高分
56   于娇莹   97   76   71  244   57   不及格    及格   低分
40   邹建志   98  104  116  318   41    及格    良好   较低
57   刘旭辉   99   87   44  230   58   不及格    及格   较低
62   孙龙基   99   21   67  187   63   不及格   不及格   低分
53   臧云飞  101   59  108  268   54   不及格    及格   低分
39   黄俊焯  101  112  106  319   40    及格    良好   较高
45   代明哲  101   91  115  307   46    及格    良好   较低
41   张俊奎  103  103  111  317   42    及格    良好   较低
35   贺俊文  103  127  110  340   36    良好    良好   较高
52   王治超  105   95   82  282   53    及格    及格   较低
43    张良  105  102  105  312   44    及格    良好   较低
37   代诗涵  105  105  126  336   38    及格    良好   较低
51    洪禹  106  100   80  286   52    及格    及格   较低
48   张家硕  107   67  129  303   49   不及格    良好   低分
50    周坤  107   76  104  287   51   不及格    及格   低分
36  张馨月小  108  110  119  337   37    及格    良好   较低
27   张智文  109  116  125  350   28    及格    良好   较高
..   ...  ...  ...  ...  ...  ...   ...   ...  ...
28    李季  114  117  118  349   29    及格    良好   较高
22  张馨月大  114  124  122  360   23    良好    良好   较高
30    何旭  114  113  120  347   31    及格    良好   较高
7    康惠雯  114  142  139  395    8    优秀    良好   高分
8    刘钰婷  115  139  135  389    9    优秀    良好   高分
38    艾宇  115  111  106  332   39    及格    良好   较低
6     刘帅  116  143  140  399    7    优秀    良好   高分
23   张曦月  116  123  119  358   24    良好    良好   较高
21   赵永刚  116  131  122  369   22    良好    良好   高分
9    林世博  116  142  129  387   10    优秀    良好   高分
24   胡丁文  116  122  118  356   25    良好    良好   较高
33   姜美慧  117  121  106  344   34    良好    良好   较高
25   赵美欣  118  126  111  355   26    良好    良好   较高
44   王春月  118   82  112  312   45   不及格    良好   低分
12   苑宇飞  118  136  131  385   13    优秀    良好   高分
17   武传禹  119  129  130  378   18    良好    良好   高分
15   范作鑫  121  127  131  379   16    良好    良好   较高
13   卢一凡  121  123  139  383   14    良好    良好   较高
20   王柏坤  121  123  128  372   21    良好    良好   较高
11    徐冲  122  124  139  385   12    良好    良好   较高
10    张希  123  130  134  387   11    良好    良好   高分
3    沙龙逸  123  148  136  407    4    优秀    优秀   高分
18   任雪桐  124  108  144  376   19    及格    良好   较低
19    刘姗  124  128  122  374   20    良好    良好   高分
14   张瑞鑫  126  115  139  380   15    及格    良好   较高
4    李鉴学  126  135  140  401    5    优秀    优秀   高分
2    韩林霖  127  139  142  408    3    优秀    优秀   高分
5    韩雨萌  129  133  138  400    6    良好    良好   高分
1     王雪  131  135  144  410    2    优秀    优秀   高分
0     杨璐  131  143  144  418    1    优秀    优秀   高分

[68 rows x 9 columns]

In [20]:
grade.sort_values('语文',ascending=False) # 降序排序

      姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深
0     杨璐  131  143  144  418    1    优秀    优秀   高分
1     王雪  131  135  144  410    2    优秀    优秀   高分
5    韩雨萌  129  133  138  400    6    良好    良好   高分
2    韩林霖  127  139  142  408    3    优秀    优秀   高分
4    李鉴学  126  135  140  401    5    优秀    优秀   高分
14   张瑞鑫  126  115  139  380   15    及格    良好   较高
19    刘姗  124  128  122  374   20    良好    良好   高分
18   任雪桐  124  108  144  376   19    及格    良好   较低
3    沙龙逸  123  148  136  407    4    优秀    优秀   高分
10    张希  123  130  134  387   11    良好    良好   高分
11    徐冲  122  124  139  385   12    良好    良好   较高
13   卢一凡  121  123  139  383   14    良好    良好   较高
15   范作鑫  121  127  131  379   16    良好    良好   较高
20   王柏坤  121  123  128  372   21    良好    良好   较高
17   武传禹  119  129  130  378   18    良好    良好   高分
12   苑宇飞  118  136  131  385   13    优秀    良好   高分
25   赵美欣  118  126  111  355   26    良好    良好   较高
44   王春月  118   82  112  312   45   不及格    良好   低分
33   姜美慧  117  121  106  344   34    良好    良好   较高
9    林世博  116  142  129  387   10    优秀    良好   高分
21   赵永刚  116  131  122  369   22    良好    良好   高分
23   张曦月  116  123  119  358   24    良好    良好   较高
24   胡丁文  116  122  118  356   25    良好    良好   较高
6     刘帅  116  143  140  399    7    优秀    良好   高分
8    刘钰婷  115  139  135  389    9    优秀    良好   高分
38    艾宇  115  111  106  332   39    及格    良好   较低
22  张馨月大  114  124  122  360   23    良好    良好   较高
7    康惠雯  114  142  139  395    8    优秀    良好   高分
28    李季  114  117  118  349   29    及格    良好   较高
30    何旭  114  113  120  347   31    及格    良好   较高
..   ...  ...  ...  ...  ...  ...   ...   ...  ...
47   狄建译  109   68  126  303   48   不及格    良好   低分
36  张馨月小  108  110  119  337   37    及格    良好   较低
48   张家硕  107   67  129  303   49   不及格    良好   低分
50    周坤  107   76  104  287   51   不及格    及格   低分
51    洪禹  106  100   80  286   52    及格    及格   较低
37   代诗涵  105  105  126  336   38    及格    良好   较低
52   王治超  105   95   82  282   53    及格    及格   较低
43    张良  105  102  105  312   44    及格    良好   较低
41   张俊奎  103  103  111  317   42    及格    良好   较低
35   贺俊文  103  127  110  340   36    良好    良好   较高
45   代明哲  101   91  115  307   46    及格    良好   较低
39   黄俊焯  101  112  106  319   40    及格    良好   较高
53   臧云飞  101   59  108  268   54   不及格    及格   低分
62   孙龙基   99   21   67  187   63   不及格   不及格   低分
57   刘旭辉   99   87   44  230   58   不及格    及格   较低
40   邹建志   98  104  116  318   41    及格    良好   较低
56   于娇莹   97   76   71  244   57   不及格    及格   低分
42    孙波   96  130   89  315   43    良好    良好   高分
55   丁婉艺   95   71   85  251   56   不及格    及格   低分
49    郭娜   94   98  104  296   50    及格    及格   较低
63    赵森   90   29   64  183   64   不及格   不及格   低分
59   黄明涛   87   77   43  207   60   不及格    及格   低分
65   李忠浩   86   32   46  164   66   不及格   不及格   低分
54   袁茂哲   85   95   85  265   55    及格    及格   较低
58   张宇婷   83   61   71  215   59   不及格    及格   低分
60   吕文卓   82   53   62  197   61   不及格   不及格   低分
61   王晟煜   79   49   64  192   62   不及格   不及格   低分
64   满朝升   78   45   47  170   65   不及格   不及格   低分
66   侯禹志   75   23   34  132   67   不及格   不及格   低分
67   尹鸿涛   66   23   34  123   68   不及格   不及格   低分

[68 rows x 9 columns]

In [22]:
grade_1 = grade.sort_values(['语文','数学'],ascending=False)

In [25]:
grade_1.reset_index(drop=True)

      姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深
0     杨璐  131  143  144  418    1    优秀    优秀   高分
1     王雪  131  135  144  410    2    优秀    优秀   高分
2    韩雨萌  129  133  138  400    6    良好    良好   高分
3    韩林霖  127  139  142  408    3    优秀    优秀   高分
4    李鉴学  126  135  140  401    5    优秀    优秀   高分
5    张瑞鑫  126  115  139  380   15    及格    良好   较高
6     刘姗  124  128  122  374   20    良好    良好   高分
7    任雪桐  124  108  144  376   19    及格    良好   较低
8    沙龙逸  123  148  136  407    4    优秀    优秀   高分
9     张希  123  130  134  387   11    良好    良好   高分
10    徐冲  122  124  139  385   12    良好    良好   较高
11   范作鑫  121  127  131  379   16    良好    良好   较高
12   卢一凡  121  123  139  383   14    良好    良好   较高
13   王柏坤  121  123  128  372   21    良好    良好   较高
14   武传禹  119  129  130  378   18    良好    良好   高分
15   苑宇飞  118  136  131  385   13    优秀    良好   高分
16   赵美欣  118  126  111  355   26    良好    良好   较高
17   王春月  118   82  112  312   45   不及格    良好   低分
18   姜美慧  117  121  106  344   34    良好    良好   较高
19    刘帅  116  143  140  399    7    优秀    良好   高分
20   林世博  116  142  129  387   10    优秀    良好   高分
21   赵永刚  116  131  122  369   22    良好    良好   高分
22   张曦月  116  123  119  358   24    良好    良好   较高
23   胡丁文  116  122  118  356   25    良好    良好   较高
24   刘钰婷  115  139  135  389    9    优秀    良好   高分
25    艾宇  115  111  106  332   39    及格    良好   较低
26   康惠雯  114  142  139  395    8    优秀    良好   高分
27  张馨月大  114  124  122  360   23    良好    良好   较高
28    李季  114  117  118  349   29    及格    良好   较高
29    何旭  114  113  120  347   31    及格    良好   较高
..   ...  ...  ...  ...  ...  ...   ...   ...  ...
38   狄建译  109   68  126  303   48   不及格    良好   低分
39  张馨月小  108  110  119  337   37    及格    良好   较低
40    周坤  107   76  104  287   51   不及格    及格   低分
41   张家硕  107   67  129  303   49   不及格    良好   低分
42    洪禹  106  100   80  286   52    及格    及格   较低
43   代诗涵  105  105  126  336   38    及格    良好   较低
44    张良  105  102  105  312   44    及格    良好   较低
45   王治超  105   95   82  282   53    及格    及格   较低
46   贺俊文  103  127  110  340   36    良好    良好   较高
47   张俊奎  103  103  111  317   42    及格    良好   较低
48   黄俊焯  101  112  106  319   40    及格    良好   较高
49   代明哲  101   91  115  307   46    及格    良好   较低
50   臧云飞  101   59  108  268   54   不及格    及格   低分
51   刘旭辉   99   87   44  230   58   不及格    及格   较低
52   孙龙基   99   21   67  187   63   不及格   不及格   低分
53   邹建志   98  104  116  318   41    及格    良好   较低
54   于娇莹   97   76   71  244   57   不及格    及格   低分
55    孙波   96  130   89  315   43    良好    良好   高分
56   丁婉艺   95   71   85  251   56   不及格    及格   低分
57    郭娜   94   98  104  296   50    及格    及格   较低
58    赵森   90   29   64  183   64   不及格   不及格   低分
59   黄明涛   87   77   43  207   60   不及格    及格   低分
60   李忠浩   86   32   46  164   66   不及格   不及格   低分
61   袁茂哲   85   95   85  265   55    及格    及格   较低
62   张宇婷   83   61   71  215   59   不及格    及格   低分
63   吕文卓   82   53   62  197   61   不及格   不及格   低分
64   王晟煜   79   49   64  192   62   不及格   不及格   低分
65   满朝升   78   45   47  170   65   不及格   不及格   低分
66   侯禹志   75   23   34  132   67   不及格   不及格   低分
67   尹鸿涛   66   23   34  123   68   不及格   不及格   低分

[68 rows x 9 columns]

2. 按索引排序

In [26]:
grade_1 = grade.sort_values(['语文','数学'],ascending=False)

In [28]:
grade_1.sort_index()

      姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深
0     杨璐  131  143  144  418    1    优秀    优秀   高分
1     王雪  131  135  144  410    2    优秀    优秀   高分
2    韩林霖  127  139  142  408    3    优秀    优秀   高分
3    沙龙逸  123  148  136  407    4    优秀    优秀   高分
4    李鉴学  126  135  140  401    5    优秀    优秀   高分
5    韩雨萌  129  133  138  400    6    良好    良好   高分
6     刘帅  116  143  140  399    7    优秀    良好   高分
7    康惠雯  114  142  139  395    8    优秀    良好   高分
8    刘钰婷  115  139  135  389    9    优秀    良好   高分
9    林世博  116  142  129  387   10    优秀    良好   高分
10    张希  123  130  134  387   11    良好    良好   高分
11    徐冲  122  124  139  385   12    良好    良好   较高
12   苑宇飞  118  136  131  385   13    优秀    良好   高分
13   卢一凡  121  123  139  383   14    良好    良好   较高
14   张瑞鑫  126  115  139  380   15    及格    良好   较高
15   范作鑫  121  127  131  379   16    良好    良好   较高
16   裴子翔  111  139  128  378   17    优秀    良好   高分
17   武传禹  119  129  130  378   18    良好    良好   高分
18   任雪桐  124  108  144  376   19    及格    良好   较低
19    刘姗  124  128  122  374   20    良好    良好   高分
20   王柏坤  121  123  128  372   21    良好    良好   较高
21   赵永刚  116  131  122  369   22    良好    良好   高分
22  张馨月大  114  124  122  360   23    良好    良好   较高
23   张曦月  116  123  119  358   24    良好    良好   较高
24   胡丁文  116  122  118  356   25    良好    良好   较高
25   赵美欣  118  126  111  355   26    良好    良好   较高
26   赵殿宇  112  109  130  351   27    及格    良好   较低
27   张智文  109  116  125  350   28    及格    良好   较高
28    李季  114  117  118  349   29    及格    良好   较高
29   杨加晖  110  102  136  348   30    及格    良好   较低
..   ...  ...  ...  ...  ...  ...   ...   ...  ...
38    艾宇  115  111  106  332   39    及格    良好   较低
39   黄俊焯  101  112  106  319   40    及格    良好   较高
40   邹建志   98  104  116  318   41    及格    良好   较低
41   张俊奎  103  103  111  317   42    及格    良好   较低
42    孙波   96  130   89  315   43    良好    良好   高分
43    张良  105  102  105  312   44    及格    良好   较低
44   王春月  118   82  112  312   45   不及格    良好   低分
45   代明哲  101   91  115  307   46    及格    良好   较低
46   张开羽  112   90  104  306   47    及格    良好   较低
47   狄建译  109   68  126  303   48   不及格    良好   低分
48   张家硕  107   67  129  303   49   不及格    良好   低分
49    郭娜   94   98  104  296   50    及格    及格   较低
50    周坤  107   76  104  287   51   不及格    及格   低分
51    洪禹  106  100   80  286   52    及格    及格   较低
52   王治超  105   95   82  282   53    及格    及格   较低
53   臧云飞  101   59  108  268   54   不及格    及格   低分
54   袁茂哲   85   95   85  265   55    及格    及格   较低
55   丁婉艺   95   71   85  251   56   不及格    及格   低分
56   于娇莹   97   76   71  244   57   不及格    及格   低分
57   刘旭辉   99   87   44  230   58   不及格    及格   较低
58   张宇婷   83   61   71  215   59   不及格    及格   低分
59   黄明涛   87   77   43  207   60   不及格    及格   低分
60   吕文卓   82   53   62  197   61   不及格   不及格   低分
61   王晟煜   79   49   64  192   62   不及格   不及格   低分
62   孙龙基   99   21   67  187   63   不及格   不及格   低分
63    赵森   90   29   64  183   64   不及格   不及格   低分
64   满朝升   78   45   47  170   65   不及格   不及格   低分
65   李忠浩   86   32   46  164   66   不及格   不及格   低分
66   侯禹志   75   23   34  132   67   不及格   不及格   低分
67   尹鸿涛   66   23   34  123   68   不及格   不及格   低分

[68 rows x 9 columns]

### 函数应用

#### map函数

map(操作函数，序列型数据）

我们使用map函数将一个函数功能应用到另一个序列数据中的每一个数据）

In [29]:
# 所有偶数除以2，所有奇数乘以2
def f(x):
    if x % 2 == 0:
        return x/2
    else:
        return x*2

In [30]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
list(map(f,r))

[0.0, 2, 1.0, 6, 2.0, 10, 3.0, 14, 4.0, 18]

In [40]:
def test(x):
    if x%3==0:
        return x/3
    elif x%2==0:
        return x/2
    else:
        return x

In [41]:
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
list(map(test,r))

[0.0, 1, 1.0, 1.0, 2.0, 5, 2.0, 7, 4.0, 3.0]

In [43]:
# 匿名函数
list(map(lambda x:x/2 if x%2==0 else x*2,r))

[0.0, 2, 1.0, 6, 2.0, 10, 3.0, 14, 4.0, 18]

In [47]:
list(map(lambda x:x/2 if x%2==0 else None,r))

[0.0, None, 1.0, None, 2.0, None, 3.0, None, 4.0, None]

In [50]:
# 列表生成式
[x/2 if x%2==0 else x*2 for x in range(10)] # 如果有else，条件判断必须放在循环之前

[0.0, 2, 1.0, 6, 2.0, 10, 3.0, 14, 4.0, 18]

In [51]:
grade.head()

    姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深
0   杨璐  131  143  144  418    1    优秀    优秀   高分
1   王雪  131  135  144  410    2    优秀    优秀   高分
2  韩林霖  127  139  142  408    3    优秀    优秀   高分
3  沙龙逸  123  148  136  407    4    优秀    优秀   高分
4  李鉴学  126  135  140  401    5    优秀    优秀   高分

In [52]:
# 小于90分的调整成90，大于90分保持不变
def f(x):
    if x<90:
        return 90
    else:
        return x

In [53]:
grade['数学调整']=grade.数学.map(f)

In [55]:
grade

      姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深  数学调整
0     杨璐  131  143  144  418    1    优秀    优秀   高分   143
1     王雪  131  135  144  410    2    优秀    优秀   高分   135
2    韩林霖  127  139  142  408    3    优秀    优秀   高分   139
3    沙龙逸  123  148  136  407    4    优秀    优秀   高分   148
4    李鉴学  126  135  140  401    5    优秀    优秀   高分   135
5    韩雨萌  129  133  138  400    6    良好    良好   高分   133
6     刘帅  116  143  140  399    7    优秀    良好   高分   143
7    康惠雯  114  142  139  395    8    优秀    良好   高分   142
8    刘钰婷  115  139  135  389    9    优秀    良好   高分   139
9    林世博  116  142  129  387   10    优秀    良好   高分   142
10    张希  123  130  134  387   11    良好    良好   高分   130
11    徐冲  122  124  139  385   12    良好    良好   较高   124
12   苑宇飞  118  136  131  385   13    优秀    良好   高分   136
13   卢一凡  121  123  139  383   14    良好    良好   较高   123
14   张瑞鑫  126  115  139  380   15    及格    良好   较高   115
15   范作鑫  121  127  131  379   16    良好    良好   较高   127
16   裴子翔  111  139  128  378   17    优秀    良好   高分   139
17   武传禹  119  129  130  378   18    良好    良好   高分   129
18   任雪桐  124  108  144  376   19    及格    良好   较低   108
19    刘姗  124  128  122  374   20    良好    良好   高分   128
20   王柏坤  121  123  128  372   21    良好    良好   较高   123
21   赵永刚  116  131  122  369   22    良好    良好   高分   131
22  张馨月大  114  124  122  360   23    良好    良好   较高   124
23   张曦月  116  123  119  358   24    良好    良好   较高   123
24   胡丁文  116  122  118  356   25    良好    良好   较高   122
25   赵美欣  118  126  111  355   26    良好    良好   较高   126
26   赵殿宇  112  109  130  351   27    及格    良好   较低   109
27   张智文  109  116  125  350   28    及格    良好   较高   116
28    李季  114  117  118  349   29    及格    良好   较高   117
29   杨加晖  110  102  136  348   30    及格    良好   较低   102
..   ...  ...  ...  ...  ...  ...   ...   ...  ...   ...
38    艾宇  115  111  106  332   39    及格    良好   较低   111
39   黄俊焯  101  112  106  319   40    及格    良好   较高   112
40   邹建志   98  104  116  318   41    及格    良好   较低   104
41   张俊奎  103  103  111  317   42    及格    良好   较低   103
42    孙波   96  130   89  315   43    良好    良好   高分   130
43    张良  105  102  105  312   44    及格    良好   较低   102
44   王春月  118   82  112  312   45   不及格    良好   低分    90
45   代明哲  101   91  115  307   46    及格    良好   较低    91
46   张开羽  112   90  104  306   47    及格    良好   较低    90
47   狄建译  109   68  126  303   48   不及格    良好   低分    90
48   张家硕  107   67  129  303   49   不及格    良好   低分    90
49    郭娜   94   98  104  296   50    及格    及格   较低    98
50    周坤  107   76  104  287   51   不及格    及格   低分    90
51    洪禹  106  100   80  286   52    及格    及格   较低   100
52   王治超  105   95   82  282   53    及格    及格   较低    95
53   臧云飞  101   59  108  268   54   不及格    及格   低分    90
54   袁茂哲   85   95   85  265   55    及格    及格   较低    95
55   丁婉艺   95   71   85  251   56   不及格    及格   低分    90
56   于娇莹   97   76   71  244   57   不及格    及格   低分    90
57   刘旭辉   99   87   44  230   58   不及格    及格   较低    90
58   张宇婷   83   61   71  215   59   不及格    及格   低分    90
59   黄明涛   87   77   43  207   60   不及格    及格   低分    90
60   吕文卓   82   53   62  197   61   不及格   不及格   低分    90
61   王晟煜   79   49   64  192   62   不及格   不及格   低分    90
62   孙龙基   99   21   67  187   63   不及格   不及格   低分    90
63    赵森   90   29   64  183   64   不及格   不及格   低分    90
64   满朝升   78   45   47  170   65   不及格   不及格   低分    90
65   李忠浩   86   32   46  164   66   不及格   不及格   低分    90
66   侯禹志   75   23   34  132   67   不及格   不及格   低分    90
67   尹鸿涛   66   23   34  123   68   不及格   不及格   低分    90

[68 rows x 10 columns]

In [56]:
# map做离散化
def test(x):
    if x<90:
        return '不及格'
    elif x<120:
        return '及格'
    elif x<135:
        return '良好'
    else:
        return '优秀'

In [57]:
grade['英语离散化']=grade.英语.map(test)
grade

      姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深  数学调整 英语离散化
0     杨璐  131  143  144  418    1    优秀    优秀   高分   143    优秀
1     王雪  131  135  144  410    2    优秀    优秀   高分   135    优秀
2    韩林霖  127  139  142  408    3    优秀    优秀   高分   139    优秀
3    沙龙逸  123  148  136  407    4    优秀    优秀   高分   148    优秀
4    李鉴学  126  135  140  401    5    优秀    优秀   高分   135    优秀
5    韩雨萌  129  133  138  400    6    良好    良好   高分   133    优秀
6     刘帅  116  143  140  399    7    优秀    良好   高分   143    优秀
7    康惠雯  114  142  139  395    8    优秀    良好   高分   142    优秀
8    刘钰婷  115  139  135  389    9    优秀    良好   高分   139    优秀
9    林世博  116  142  129  387   10    优秀    良好   高分   142    良好
10    张希  123  130  134  387   11    良好    良好   高分   130    良好
11    徐冲  122  124  139  385   12    良好    良好   较高   124    优秀
12   苑宇飞  118  136  131  385   13    优秀    良好   高分   136    良好
13   卢一凡  121  123  139  383   14    良好    良好   较高   123    优秀
14   张瑞鑫  126  115  139  380   15    及格    良好   较高   115    优秀
15   范作鑫  121  127  131  379   16    良好    良好   较高   127    良好
16   裴子翔  111  139  128  378   17    优秀    良好   高分   139    良好
17   武传禹  119  129  130  378   18    良好    良好   高分   129    良好
18   任雪桐  124  108  144  376   19    及格    良好   较低   108    优秀
19    刘姗  124  128  122  374   20    良好    良好   高分   128    良好
20   王柏坤  121  123  128  372   21    良好    良好   较高   123    良好
21   赵永刚  116  131  122  369   22    良好    良好   高分   131    良好
22  张馨月大  114  124  122  360   23    良好    良好   较高   124    良好
23   张曦月  116  123  119  358   24    良好    良好   较高   123    及格
24   胡丁文  116  122  118  356   25    良好    良好   较高   122    及格
25   赵美欣  118  126  111  355   26    良好    良好   较高   126    及格
26   赵殿宇  112  109  130  351   27    及格    良好   较低   109    良好
27   张智文  109  116  125  350   28    及格    良好   较高   116    良好
28    李季  114  117  118  349   29    及格    良好   较高   117    及格
29   杨加晖  110  102  136  348   30    及格    良好   较低   102    优秀
..   ...  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
38    艾宇  115  111  106  332   39    及格    良好   较低   111    及格
39   黄俊焯  101  112  106  319   40    及格    良好   较高   112    及格
40   邹建志   98  104  116  318   41    及格    良好   较低   104    及格
41   张俊奎  103  103  111  317   42    及格    良好   较低   103    及格
42    孙波   96  130   89  315   43    良好    良好   高分   130   不及格
43    张良  105  102  105  312   44    及格    良好   较低   102    及格
44   王春月  118   82  112  312   45   不及格    良好   低分    90    及格
45   代明哲  101   91  115  307   46    及格    良好   较低    91    及格
46   张开羽  112   90  104  306   47    及格    良好   较低    90    及格
47   狄建译  109   68  126  303   48   不及格    良好   低分    90    良好
48   张家硕  107   67  129  303   49   不及格    良好   低分    90    良好
49    郭娜   94   98  104  296   50    及格    及格   较低    98    及格
50    周坤  107   76  104  287   51   不及格    及格   低分    90    及格
51    洪禹  106  100   80  286   52    及格    及格   较低   100   不及格
52   王治超  105   95   82  282   53    及格    及格   较低    95   不及格
53   臧云飞  101   59  108  268   54   不及格    及格   低分    90    及格
54   袁茂哲   85   95   85  265   55    及格    及格   较低    95   不及格
55   丁婉艺   95   71   85  251   56   不及格    及格   低分    90   不及格
56   于娇莹   97   76   71  244   57   不及格    及格   低分    90   不及格
57   刘旭辉   99   87   44  230   58   不及格    及格   较低    90   不及格
58   张宇婷   83   61   71  215   59   不及格    及格   低分    90   不及格
59   黄明涛   87   77   43  207   60   不及格    及格   低分    90   不及格
60   吕文卓   82   53   62  197   61   不及格   不及格   低分    90   不及格
61   王晟煜   79   49   64  192   62   不及格   不及格   低分    90   不及格
62   孙龙基   99   21   67  187   63   不及格   不及格   低分    90   不及格
63    赵森   90   29   64  183   64   不及格   不及格   低分    90   不及格
64   满朝升   78   45   47  170   65   不及格   不及格   低分    90   不及格
65   李忠浩   86   32   46  164   66   不及格   不及格   低分    90   不及格
66   侯禹志   75   23   34  132   67   不及格   不及格   低分    90   不及格
67   尹鸿涛   66   23   34  123   68   不及格   不及格   低分    90   不及格

[68 rows x 11 columns]

In [59]:
grade.姓名[0][0]

'杨'

In [60]:
# 提取姓氏
grade['姓氏']=grade.姓名.map(lambda x:x[0])

In [62]:
# 提取名
grade['名']=grade.姓名.map(lambda x:x[1:])
grade.head()

    姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深  数学调整 英语离散化 姓氏   名
0   杨璐  131  143  144  418    1    优秀    优秀   高分   143    优秀  杨   璐
1   王雪  131  135  144  410    2    优秀    优秀   高分   135    优秀  王   雪
2  韩林霖  127  139  142  408    3    优秀    优秀   高分   139    优秀  韩  林霖
3  沙龙逸  123  148  136  407    4    优秀    优秀   高分   148    优秀  沙  龙逸
4  李鉴学  126  135  140  401    5    优秀    优秀   高分   135    优秀  李  鉴学

#### apply函数

In [63]:
grade2 = grade[['语文','数学','英语']]
grade2.head()

    语文   数学   英语
0  131  143  144
1  131  135  144
2  127  139  142
3  123  148  136
4  126  135  140

In [64]:
# 算每一行总分
grade2.apply(np.sum,axis=1)

0     418
1     410
2     408
3     407
4     401
5     400
6     399
7     395
8     389
9     387
10    387
11    385
12    385
13    383
14    380
15    379
16    378
17    378
18    376
19    374
20    372
21    369
22    360
23    358
24    356
25    355
26    351
27    350
28    349
29    348
     ...
38    332
39    319
40    318
41    317
42    315
43    312
44    312
45    307
46    306
47    303
48    303
49    296
50    287
51    286
52    282
53    268
54    265
55    251
56    244
57    230
58    215
59    207
60    197
61    192
62    187
63    183
64    170
65    164
66    132
67    123
Length: 68, dtype: int64

#### applymap函数

In [66]:
# isinstance 类型判断
a ='asd'
isinstance(a,int)

False

In [68]:
def f(x):
    if isinstance(x,str):
        return x[0]
    elif isinstance(x,int):
        return x/100
    else:
        return x

In [70]:
grade.applymap(f)

   姓名    语文    数学    英语    总分   班名次 数学离散化 总分离散化 数学等深  数学调整 英语离散化 姓氏  名
0   杨  1.31  1.43  1.44  4.18  0.01     优     优    高  1.43     优  杨  璐
1   王  1.31  1.35  1.44  4.10  0.02     优     优    高  1.35     优  王  雪
2   韩  1.27  1.39  1.42  4.08  0.03     优     优    高  1.39     优  韩  林
3   沙  1.23  1.48  1.36  4.07  0.04     优     优    高  1.48     优  沙  龙
4   李  1.26  1.35  1.40  4.01  0.05     优     优    高  1.35     优  李  鉴
5   韩  1.29  1.33  1.38  4.00  0.06     良     良    高  1.33     优  韩  雨
6   刘  1.16  1.43  1.40  3.99  0.07     优     良    高  1.43     优  刘  帅
7   康  1.14  1.42  1.39  3.95  0.08     优     良    高  1.42     优  康  惠
8   刘  1.15  1.39  1.35  3.89  0.09     优     良    高  1.39     优  刘  钰
9   林  1.16  1.42  1.29  3.87  0.10     优     良    高  1.42     良  林  世
10  张  1.23  1.30  1.34  3.87  0.11     良     良    高  1.30     良  张  希
11  徐  1.22  1.24  1.39  3.85  0.12     良     良    较  1.24     优  徐  冲
12  苑  1.18  1.36  1.31  3.85  0.13     优     良    高  1.36     良  苑  宇
13  卢  1.21  1.23  1.39  3.83  0.14     良     良    较  1.23     优  卢  一
14  张  1.26  1.15  1.39  3.80  0.15     及     良    较  1.15     优  张  瑞
15  范  1.21  1.27  1.31  3.79  0.16     良     良    较  1.27     良  范  作
16  裴  1.11  1.39  1.28  3.78  0.17     优     良    高  1.39     良  裴  子
17  武  1.19  1.29  1.30  3.78  0.18     良     良    高  1.29     良  武  传
18  任  1.24  1.08  1.44  3.76  0.19     及     良    较  1.08     优  任  雪
19  刘  1.24  1.28  1.22  3.74  0.20     良     良    高  1.28     良  刘  姗
20  王  1.21  1.23  1.28  3.72  0.21     良     良    较  1.23     良  王  柏
21  赵  1.16  1.31  1.22  3.69  0.22     良     良    高  1.31     良  赵  永
22  张  1.14  1.24  1.22  3.60  0.23     良     良    较  1.24     良  张  馨
23  张  1.16  1.23  1.19  3.58  0.24     良     良    较  1.23     及  张  曦
24  胡  1.16  1.22  1.18  3.56  0.25     良     良    较  1.22     及  胡  丁
25  赵  1.18  1.26  1.11  3.55  0.26     良     良    较  1.26     及  赵  美
26  赵  1.12  1.09  1.30  3.51  0.27     及     良    较  1.09     良  赵  殿
27  张  1.09  1.16  1.25  3.50  0.28     及     良    较  1.16     良  张  智
28  李  1.14  1.17  1.18  3.49  0.29     及     良    较  1.17     及  李  季
29  杨  1.10  1.02  1.36  3.48  0.30     及     良    较  1.02     优  杨  加
.. ..   ...   ...   ...   ...   ...   ...   ...  ...   ...   ... .. ..
38  艾  1.15  1.11  1.06  3.32  0.39     及     良    较  1.11     及  艾  宇
39  黄  1.01  1.12  1.06  3.19  0.40     及     良    较  1.12     及  黄  俊
40  邹  0.98  1.04  1.16  3.18  0.41     及     良    较  1.04     及  邹  建
41  张  1.03  1.03  1.11  3.17  0.42     及     良    较  1.03     及  张  俊
42  孙  0.96  1.30  0.89  3.15  0.43     良     良    高  1.30     不  孙  波
43  张  1.05  1.02  1.05  3.12  0.44     及     良    较  1.02     及  张  良
44  王  1.18  0.82  1.12  3.12  0.45     不     良    低  0.90     及  王  春
45  代  1.01  0.91  1.15  3.07  0.46     及     良    较  0.91     及  代  明
46  张  1.12  0.90  1.04  3.06  0.47     及     良    较  0.90     及  张  开
47  狄  1.09  0.68  1.26  3.03  0.48     不     良    低  0.90     良  狄  建
48  张  1.07  0.67  1.29  3.03  0.49     不     良    低  0.90     良  张  家
49  郭  0.94  0.98  1.04  2.96  0.50     及     及    较  0.98     及  郭  娜
50  周  1.07  0.76  1.04  2.87  0.51     不     及    低  0.90     及  周  坤
51  洪  1.06  1.00  0.80  2.86  0.52     及     及    较  1.00     不  洪  禹
52  王  1.05  0.95  0.82  2.82  0.53     及     及    较  0.95     不  王  治
53  臧  1.01  0.59  1.08  2.68  0.54     不     及    低  0.90     及  臧  云
54  袁  0.85  0.95  0.85  2.65  0.55     及     及    较  0.95     不  袁  茂
55  丁  0.95  0.71  0.85  2.51  0.56     不     及    低  0.90     不  丁  婉
56  于  0.97  0.76  0.71  2.44  0.57     不     及    低  0.90     不  于  娇
57  刘  0.99  0.87  0.44  2.30  0.58     不     及    较  0.90     不  刘  旭
58  张  0.83  0.61  0.71  2.15  0.59     不     及    低  0.90     不  张  宇
59  黄  0.87  0.77  0.43  2.07  0.60     不     及    低  0.90     不  黄  明
60  吕  0.82  0.53  0.62  1.97  0.61     不     不    低  0.90     不  吕  文
61  王  0.79  0.49  0.64  1.92  0.62     不     不    低  0.90     不  王  晟
62  孙  0.99  0.21  0.67  1.87  0.63     不     不    低  0.90     不  孙  龙
63  赵  0.90  0.29  0.64  1.83  0.64     不     不    低  0.90     不  赵  森
64  满  0.78  0.45  0.47  1.70  0.65     不     不    低  0.90     不  满  朝
65  李  0.86  0.32  0.46  1.64  0.66     不     不    低  0.90     不  李  忠
66  侯  0.75  0.23  0.34  1.32  0.67     不     不    低  0.90     不  侯  禹
67  尹  0.66  0.23  0.34  1.23  0.68     不     不    低  0.90     不  尹  鸿

[68 rows x 13 columns]

### 表的合并

In [7]:
  columns = ['年龄','星座','身高']
data = [
    [30,'白羊座','180cm'],
    [27,'金牛座','170cm'],
    [32,'双子座','175cm'],
    [25,'巨蟹座','170cm'],
    [28,'狮子座','160cm'],
    [31,'双鱼座','165cm']  
]

index = ['A','B','C','D','E','F']
df = pd.DataFrame(data=data,index=index,columns=columns)
df

   年龄   星座     身高
A  30  白羊座  180cm
B  27  金牛座  170cm
C  32  双子座  175cm
D  25  巨蟹座  170cm
E  28  狮子座  160cm
F  31  双鱼座  165cm

In [72]:
columns = ['年龄','星座','身高']
data = [
    [30,'白羊座','180cm'],
    [27,'金牛座','170cm'],
    [32,'双子座','175cm'],
    [25,'巨蟹座','170cm'],
    [28,'狮子座','160cm'],
    [31,'双鱼座','165cm']  
]

index = ['AA','BB','CC','DD','EE','FF']
df2 = pd.DataFrame(data=data,index=index,columns=columns)

#### append方法

In [74]:
df.append(df2)

    年龄   星座     身高
A   30  白羊座  180cm
B   27  金牛座  170cm
C   32  双子座  175cm
D   25  巨蟹座  170cm
E   28  狮子座  160cm
F   31  双鱼座  165cm
AA  30  白羊座  180cm
BB  27  金牛座  170cm
CC  32  双子座  175cm
DD  25  巨蟹座  170cm
EE  28  狮子座  160cm
FF  31  双鱼座  165cm

In [75]:
df.append([df2,df,df,df2])

    年龄   星座     身高
A   30  白羊座  180cm
B   27  金牛座  170cm
C   32  双子座  175cm
D   25  巨蟹座  170cm
E   28  狮子座  160cm
F   31  双鱼座  165cm
AA  30  白羊座  180cm
BB  27  金牛座  170cm
CC  32  双子座  175cm
DD  25  巨蟹座  170cm
EE  28  狮子座  160cm
FF  31  双鱼座  165cm
A   30  白羊座  180cm
B   27  金牛座  170cm
C   32  双子座  175cm
D   25  巨蟹座  170cm
E   28  狮子座  160cm
F   31  双鱼座  165cm
A   30  白羊座  180cm
B   27  金牛座  170cm
C   32  双子座  175cm
D   25  巨蟹座  170cm
E   28  狮子座  160cm
F   31  双鱼座  165cm
AA  30  白羊座  180cm
BB  27  金牛座  170cm
CC  32  双子座  175cm
DD  25  巨蟹座  170cm
EE  28  狮子座  160cm
FF  31  双鱼座  165cm

In [76]:
df.append([df2,df],verify_integrity=True) # 遇到重复值，就会报错

ValueError: Indexes have overlapping values: Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

#### concat方法

In [77]:
grade_one=grade.loc[0:6]
grade_two = grade.loc[4:10]

In [78]:
grade_one

    姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深  数学调整 英语离散化 姓氏   名
0   杨璐  131  143  144  418    1    优秀    优秀   高分   143    优秀  杨   璐
1   王雪  131  135  144  410    2    优秀    优秀   高分   135    优秀  王   雪
2  韩林霖  127  139  142  408    3    优秀    优秀   高分   139    优秀  韩  林霖
3  沙龙逸  123  148  136  407    4    优秀    优秀   高分   148    优秀  沙  龙逸
4  李鉴学  126  135  140  401    5    优秀    优秀   高分   135    优秀  李  鉴学
5  韩雨萌  129  133  138  400    6    良好    良好   高分   133    优秀  韩  雨萌
6   刘帅  116  143  140  399    7    优秀    良好   高分   143    优秀  刘   帅

In [79]:
grade_two

     姓名   语文   数学   英语   总分  班名次 数学离散化 总分离散化 数学等深  数学调整 英语离散化 姓氏   名
4   李鉴学  126  135  140  401    5    优秀    优秀   高分   135    优秀  李  鉴学
5   韩雨萌  129  133  138  400    6    良好    良好   高分   133    优秀  韩  雨萌
6    刘帅  116  143  140  399    7    优秀    良好   高分   143    优秀  刘   帅
7   康惠雯  114  142  139  395    8    优秀    良好   高分   142    优秀  康  惠雯
8   刘钰婷  115  139  135  389    9    优秀    良好   高分   139    优秀  刘  钰婷
9   林世博  116  142  129  387   10    优秀    良好   高分   142    良好  林  世博
10   张希  123  130  134  387   11    良好    良好   高分   130    良好  张   希

In [80]:
# 横向拼接
pd.concat([grade_one,grade_two],axis=1)

,姓名,语文,数学,英语,总分,班名次,数学离散化,总分离散化,数学等深,数学调整,...,英语,总分,班名次,数学离散化,总分离散化,数学等深,数学调整,英语离散化,姓氏,名
0,杨璐,131.0,143.0,144.0,418.0,1.0,优秀,优秀,高分,143.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,王雪,131.0,135.0,144.0,410.0,2.0,优秀,优秀,高分,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,韩林霖,127.0,139.0,142.0,408.0,3.0,优秀,优秀,高分,139.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,沙龙逸,123.0,148.0,136.0,407.0,4.0,优秀,优秀,高分,148.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,李鉴学,126.0,135.0,140.0,401.0,5.0,优秀,优秀,高分,135.0,...,140.0,401.0,5.0,优秀,优秀,高分,135.0,优秀,李,鉴学
5,韩雨萌,129.0,133.0,138.0,400.0,6.0,良好,良好,高分,133.0,...,138.0,400.0,6.0,良好,良好,高分,133.0,优秀,韩,雨萌
6,刘帅,116.0,143.0,140.0,399.0,7.0,优秀,良好,高分,143.0,...,140.0,399.0,7.0,优秀,良好,高分,143.0,优秀,刘,帅
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,139.0,395.0,8.0,优秀,良好,高分,142.0,优秀,康,惠雯
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,135.0,389.0,9.0,优秀,良好,高分,139.0,优秀,刘,钰婷
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,129.0,387.0,10.0,优秀,良好,高分,142.0,良好,林,世博
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,134.0,387.0,11.0,良好,良好,高分,130.0,良好,张,希

In [81]:
pd.concat([grade_one,grade_two],axis=1,join='inner')

,姓名,语文,数学,英语,总分,班名次,数学离散化,总分离散化,数学等深,数学调整,...,英语,总分,班名次,数学离散化,总分离散化,数学等深,数学调整,英语离散化,姓氏,名
4,李鉴学,126,135,140,401,5,优秀,优秀,高分,135,...,140,401,5,优秀,优秀,高分,135,优秀,李,鉴学
5,韩雨萌,129,133,138,400,6,良好,良好,高分,133,...,138,400,6,良好,良好,高分,133,优秀,韩,雨萌
6,刘帅,116,143,140,399,7,优秀,良好,高分,143,...,140,399,7,优秀,良好,高分,143,优秀,刘,帅

#### merge方法

In [82]:
grade_1=grade_one[['姓名','数学','语文','英语']]
grade_2=grade_two[['姓名','数学','总分','班名次']]

In [83]:
pd.merge(grade_1,grade_2)

    姓名   数学   语文   英语   总分  班名次
0  李鉴学  135  126  140  401    5
1  韩雨萌  133  129  138  400    6
2   刘帅  143  116  140  399    7

In [84]:
pd.merge(grade_1,grade_2,how='outer')

     姓名   数学     语文     英语     总分   班名次
0    杨璐  143  131.0  144.0    NaN   NaN
1    王雪  135  131.0  144.0    NaN   NaN
2   韩林霖  139  127.0  142.0    NaN   NaN
3   沙龙逸  148  123.0  136.0    NaN   NaN
4   李鉴学  135  126.0  140.0  401.0   5.0
5   韩雨萌  133  129.0  138.0  400.0   6.0
6    刘帅  143  116.0  140.0  399.0   7.0
7   康惠雯  142    NaN    NaN  395.0   8.0
8   刘钰婷  139    NaN    NaN  389.0   9.0
9   林世博  142    NaN    NaN  387.0  10.0
10   张希  130    NaN    NaN  387.0  11.0

In [86]:
pd.merge(grade_1,grade_2,how='left',on='姓名')

    姓名  数学_x   语文   英语   数学_y     总分  班名次
0   杨璐   143  131  144    NaN    NaN  NaN
1   王雪   135  131  144    NaN    NaN  NaN
2  韩林霖   139  127  142    NaN    NaN  NaN
3  沙龙逸   148  123  136    NaN    NaN  NaN
4  李鉴学   135  126  140  135.0  401.0  5.0
5  韩雨萌   133  129  138  133.0  400.0  6.0
6   刘帅   143  116  140  143.0  399.0  7.0

In [89]:
pd.merge(grade_1,grade_2,how='left',on='姓名',suffixes=['_左表','_右表'])

    姓名  数学_左表   语文   英语  数学_右表     总分  班名次
0   杨璐    143  131  144    NaN    NaN  NaN
1   王雪    135  131  144    NaN    NaN  NaN
2  韩林霖    139  127  142    NaN    NaN  NaN
3  沙龙逸    148  123  136    NaN    NaN  NaN
4  李鉴学    135  126  140  135.0  401.0  5.0
5  韩雨萌    133  129  138  133.0  400.0  6.0
6   刘帅    143  116  140  143.0  399.0  7.0

In [90]:
grade_3 = grade_2.rename(columns={'姓名':'学生姓名'})
grade_3

   学生姓名   数学   总分  班名次
4   李鉴学  135  401    5
5   韩雨萌  133  400    6
6    刘帅  143  399    7
7   康惠雯  142  395    8
8   刘钰婷  139  389    9
9   林世博  142  387   10
10   张希  130  387   11

In [92]:
pd.merge(grade_1,grade_3,how='left',left_on='姓名',right_on='学生姓名')

    姓名  数学_x   语文   英语 学生姓名   数学_y     总分  班名次
0   杨璐   143  131  144  NaN    NaN    NaN  NaN
1   王雪   135  131  144  NaN    NaN    NaN  NaN
2  韩林霖   139  127  142  NaN    NaN    NaN  NaN
3  沙龙逸   148  123  136  NaN    NaN    NaN  NaN
4  李鉴学   135  126  140  李鉴学  135.0  401.0  5.0
5  韩雨萌   133  129  138  韩雨萌  133.0  400.0  6.0
6   刘帅   143  116  140   刘帅  143.0  399.0  7.0

In [93]:
pd.merge(grade_1,grade_2,how='outer',indicator=True)

     姓名   数学     语文     英语     总分   班名次      _merge
0    杨璐  143  131.0  144.0    NaN   NaN   left_only
1    王雪  135  131.0  144.0    NaN   NaN   left_only
2   韩林霖  139  127.0  142.0    NaN   NaN   left_only
3   沙龙逸  148  123.0  136.0    NaN   NaN   left_only
4   李鉴学  135  126.0  140.0  401.0   5.0        both
5   韩雨萌  133  129.0  138.0  400.0   6.0        both
6    刘帅  143  116.0  140.0  399.0   7.0        both
7   康惠雯  142    NaN    NaN  395.0   8.0  right_only
8   刘钰婷  139    NaN    NaN  389.0   9.0  right_only
9   林世博  142    NaN    NaN  387.0  10.0  right_only
10   张希  130    NaN    NaN  387.0  11.0  right_only